"""
Constants and choices for notifications app
"""

# Notification Type
NOTIFICATION_FLIGHT = 'FLIGHT'
NOTIFICATION_BOOKING = 'BOOKING'
NOTIFICATION_PAYMENT = 'PAYMENT'
NOTIFICATION_PROMOTION = 'PROMOTION'
NOTIFICATION_SECURITY = 'SECURITY'
NOTIFICATION_SYSTEM = 'SYSTEM'

NOTIFICATION_TYPE_CHOICES = [
    (NOTIFICATION_FLIGHT, 'پرواز'),
    (NOTIFICATION_BOOKING, 'رزرو'),
    (NOTIFICATION_PAYMENT, 'پرداخت'),
    (NOTIFICATION_PROMOTION, 'پیشنهاد ویژه'),
    (NOTIFICATION_SECURITY, 'امنیتی'),
    (NOTIFICATION_SYSTEM, 'سیستمی'),
]

# Notification Channel
CHANNEL_EMAIL = 'EMAIL'
CHANNEL_SMS = 'SMS'
CHANNEL_PUSH = 'PUSH'
CHANNEL_IN_APP = 'IN_APP'
CHANNEL_PHONE = 'PHONE'

NOTIFICATION_CHANNEL_CHOICES = [
    (CHANNEL_EMAIL, 'ایمیل'),
    (CHANNEL_SMS, 'پیامک'),
    (CHANNEL_PUSH, 'Push Notification'),
    (CHANNEL_IN_APP, 'درون برنامه'),
    (CHANNEL_PHONE, 'تماس تلفنی'),
]

# Notification Status
NOTIFICATION_PENDING = 'PENDING'
NOTIFICATION_SENT = 'SENT'
NOTIFICATION_DELIVERED = 'DELIVERED'
NOTIFICATION_FAILED = 'FAILED'
NOTIFICATION_READ = 'READ'

NOTIFICATION_STATUS_CHOICES = [
    (NOTIFICATION_PENDING, 'در انتظار'),
    (NOTIFICATION_SENT, 'ارسال شده'),
    (NOTIFICATION_DELIVERED, 'تحویل داده شده'),
    (NOTIFICATION_FAILED, 'ناموفق'),
    (NOTIFICATION_READ, 'خوانده شده'),
]

# Notification Priority
PRIORITY_LOW = 'LOW'
PRIORITY_NORMAL = 'NORMAL'
PRIORITY_HIGH = 'HIGH'
PRIORITY_URGENT = 'URGENT'

NOTIFICATION_PRIORITY_CHOICES = [
    (PRIORITY_LOW, 'پایین'),
    (PRIORITY_NORMAL, 'عادی'),
    (PRIORITY_HIGH, 'بالا'),
    (PRIORITY_URGENT, 'فوری'),
]

# Default Values
DEFAULT_NOTIFICATION_STATUS = NOTIFICATION_PENDING
DEFAULT_NOTIFICATION_PRIORITY = PRIORITY_NORMAL
DEFAULT_NOTIFICATION_CHANNEL = CHANNEL_EMAIL

