# Generated by Django 5.2.6 on 2025-11-18 13:40

import django.core.validators
import django.db.models.deletion
import payments.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True, validators=[payments.validators.validate_transaction_id], verbose_name='شناسه تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[payments.validators.validate_payment_amount], verbose_name='مبلغ')),
                ('method', models.CharField(choices=[('ONLINE', 'پرداخت آنلاین'), ('CARD', 'کارت بانکی'), ('WALLET', 'کیف پول الکترونیکی'), ('CRYPTO', 'ارز دیجیتال'), ('INSTALLMENT', 'اقساطی'), ('CASH', 'نقدی')], default='ONLINE', max_length=20, verbose_name='روش پرداخت')),
                ('gateway', models.CharField(blank=True, choices=[('BANK_MELI', 'بانک ملی'), ('BANK_PARSIAN', 'بانک پارسیان'), ('BANK_MELLAT', 'بانک ملت'), ('BANK_SADERAT', 'بانک صادرات'), ('BANK_TEJARAT', 'بانک تجارت'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('ZARINPAL', 'زرین\u200cپال')], max_length=50, null=True, verbose_name='درگاه پرداخت')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'ناموفق'), ('CANCELLED', 'لغو شده'), ('REFUNDED', 'بازپرداخت شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش درگاه')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ درگاه')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد خطا')),
                ('is_installment', models.BooleanField(default=False, verbose_name='اقساطی')),
                ('installment_months', models.IntegerField(blank=True, null=True, verbose_name='تعداد اقساط')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قسط ماهانه')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='رزرو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'پرداخت'), ('REFUND', 'بازپرداخت'), ('PARTIAL_REFUND', 'بازپرداخت جزئی'), ('CHARGEBACK', 'برگشت وجه')], default='PAYMENT', max_length=20, verbose_name='نوع تراکنش')),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True, validators=[payments.validators.validate_transaction_id], verbose_name='شناسه تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'ناموفق'), ('CANCELLED', 'لغو شده'), ('REFUNDED', 'بازپرداخت شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('gateway', models.CharField(blank=True, choices=[('BANK_MELI', 'بانک ملی'), ('BANK_PARSIAN', 'بانک پارسیان'), ('BANK_MELLAT', 'بانک ملت'), ('BANK_SADERAT', 'بانک صادرات'), ('BANK_TEJARAT', 'بانک تجارت'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('ZARINPAL', 'زرین\u200cپال')], max_length=50, null=True, verbose_name='درگاه پرداخت')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش درگاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ بازپرداخت')),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='درصد بازپرداخت')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='دلیل بازپرداخت')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'ناموفق'), ('CANCELLED', 'لغو شده'), ('REFUNDED', 'بازپرداخت شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('gateway_refund_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه بازپرداخت درگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='پرداخت')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='payments.transaction', verbose_name='تراکنش')),
            ],
            options={
                'verbose_name': 'بازپرداخت',
                'verbose_name_plural': 'بازپرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_fb31b8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='payments_tr_transac_e96a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment', 'transaction_type'], name='payments_tr_payment_2793b0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_tr_status_e3597b_idx'),
        ),
    ]
