# Generated by Django 5.2.6 on 2025-11-22 11:54

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_ip_booking_metadata_booking_uuid_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='آی\u200cپی پرداخت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['uuid'], name='payments_pa_uuid_cf872a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_ip'], name='payments_pa_payment_477ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['uuid'], name='payments_tr_uuid_510d6c_idx'),
        ),
    ]
