# Generated by Django 5.2.6 on 2026-02-04 10:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مهمان')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل مهمان')),
                ('session_id', models.CharField(db_index=True, help_text='شناسه یکتای نشست چت', max_length=255, unique=True, verbose_name='شناسه نشست')),
                ('status', models.CharField(choices=[('OPEN', 'باز'), ('WAITING', 'در انتظار'), ('IN_PROGRESS', 'در حال بررسی'), ('CLOSED', 'بسته شده')], db_index=True, default='OPEN', max_length=20, verbose_name='وضعیت')),
                ('customer_tier', models.CharField(choices=[('GOLD', 'طلا'), ('SILVER', 'نقره'), ('BRONZE', 'برنز')], db_index=True, default='BRONZE', help_text='سطح مشتری در زمان شروع چت', max_length=20, verbose_name='سطح مشتری')),
                ('nira_session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='شناسه نشست در نیرا')),
                ('nira_data', models.JSONField(blank=True, default=dict, help_text='اطلاعات دریافتی از سیستم نیرا', verbose_name='اطلاعات نیرا')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی کلاینت')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='پرسنل پشتیبانی که این چت را مدیریت می\u200cکند', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص داده شده به')),
                ('user', models.ForeignKey(blank=True, help_text='کاربر لاگین شده (اگر مهمان باشد، خالی می\u200cماند)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نشست چت',
                'verbose_name_plural': 'نشست\u200cهای چت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('message', models.TextField(help_text='متن پیام', verbose_name='پیام')),
                ('message_type', models.CharField(choices=[('CUSTOMER', 'مشتری'), ('STAFF', 'پرسنل'), ('SYSTEM', 'سیستم')], db_index=True, default='CUSTOMER', max_length=20, verbose_name='نوع پیام')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده')),
                ('message_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی ارسال پیام')),
                ('nira_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پیام در نیرا')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(blank=True, help_text='ارسال\u200cکننده پیام (اگر از پرسنل باشد)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_service_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer_service.chatsession', verbose_name='نشست چت')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': 'پیام\u200cهای چت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTierSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('tier', models.CharField(choices=[('GOLD', 'طلا'), ('SILVER', 'نقره'), ('BRONZE', 'برنز')], db_index=True, help_text='سطح مشتری (طلا، نقره، برنز)', max_length=20, verbose_name='سطح مشتری')),
                ('criteria_type', models.CharField(choices=[('TOTAL_PURCHASE_AMOUNT', 'مبلغ کل خرید'), ('TOTAL_BOOKINGS_COUNT', 'تعداد کل رزروها'), ('MONTHLY_PURCHASE_AMOUNT', 'مبلغ خرید ماهانه'), ('DAYS_SINCE_REGISTRATION', 'روز از زمان ثبت\u200cنام'), ('LAST_PURCHASE_DAYS', 'روز از آخرین خرید')], help_text='نوع معیار برای تقسیم\u200cبندی (مثال: مبلغ کل خرید)', max_length=50, verbose_name='نوع معیار')),
                ('operator', models.CharField(choices=[('GT', 'بزرگتر از'), ('GTE', 'بزرگتر یا مساوی با'), ('LT', 'کوچکتر از'), ('LTE', 'کوچکتر یا مساوی با'), ('EQ', 'مساوی با')], help_text='عملگر مقایسه (بزرگتر از، مساوی با و...)', max_length=10, verbose_name='عملگر مقایسه')),
                ('value', models.DecimalField(decimal_places=2, help_text='مقدار معیار (مثال: برای مبلغ کل خرید، مقدار به تومان)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی برای این تنظیمات', verbose_name='توضیحات')),
                ('priority', models.PositiveIntegerField(default=0, help_text='اولویت بررسی (عدد بیشتر = اولویت بالاتر)', verbose_name='اولویت')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='اگر فعال نباشد، این معیار در محاسبه استفاده نمی\u200cشود', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سطح مشتری',
                'verbose_name_plural': 'تنظیمات سطوح مشتری',
                'ordering': ['-priority', 'tier'],
                'indexes': [models.Index(fields=['tier', 'is_active'], name='customer_se_tier_5661e7_idx'), models.Index(fields=['is_active', 'priority'], name='customer_se_is_acti_c05adc_idx'), models.Index(fields=['criteria_type', 'is_active'], name='customer_se_criteri_1ed188_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'status'], name='customer_se_user_id_e99a33_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status', 'created_at'], name='customer_se_status_1326bb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['assigned_to', 'status'], name='customer_se_assigne_07a898_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['customer_tier', 'status'], name='customer_se_custome_80cb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='customer_se_session_2ec4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='customer_se_session_c03d62_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'created_at'], name='customer_se_user_id_7d083e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type', 'is_read'], name='customer_se_message_d200ef_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read', 'created_at'], name='customer_se_is_read_e9966b_idx'),
        ),
    ]
