# Generated by Django 4.2.2 on 2026-02-08 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightMealFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('flight_number', models.CharField(blank=True, help_text='شماره پرواز (مثال: NSN6650)', max_length=20, null=True, verbose_name='شماره پرواز')),
                ('origin_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر مبدا')),
                ('destination_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر مقصد')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('food_quality', models.IntegerField(blank=True, choices=[(5, 'عالی'), (4, 'خوب'), (3, 'متوسط'), (2, 'ضعیف'), (1, 'بسیار ضعیف')], help_text='رتبه\u200cبندی کلی کیفیت غذا', null=True, verbose_name='کیفیت غذا')),
                ('food_temperature', models.IntegerField(blank=True, choices=[(5, 'عالی'), (4, 'خوب'), (3, 'متوسط'), (2, 'ضعیف'), (1, 'بسیار ضعیف')], help_text='آیا غذا در دمای مناسب سرو شد؟', null=True, verbose_name='دمای غذا')),
                ('food_taste', models.IntegerField(blank=True, choices=[(5, 'عالی'), (4, 'خوب'), (3, 'متوسط'), (2, 'ضعیف'), (1, 'بسیار ضعیف')], help_text='طعم و مزه غذا', null=True, verbose_name='طعم غذا')),
                ('food_presentation', models.IntegerField(blank=True, choices=[(5, 'عالی'), (4, 'خوب'), (3, 'متوسط'), (2, 'ضعیف'), (1, 'بسیار ضعیف')], help_text='ظاهر و نحوه چیدمان غذا', null=True, verbose_name='نحوه ارائه غذا')),
                ('portion_size', models.IntegerField(blank=True, choices=[(5, 'عالی'), (4, 'خوب'), (3, 'متوسط'), (2, 'ضعیف'), (1, 'بسیار ضعیف')], help_text='آیا مقدار غذا کافی بود؟', null=True, verbose_name='اندازه پرس')),
                ('variety', models.IntegerField(blank=True, choices=[(5, 'عالی'), (4, 'خوب'), (3, 'متوسط'), (2, 'ضعیف'), (1, 'بسیار ضعیف')], help_text='تنوع و گزینه\u200cهای غذایی', null=True, verbose_name='تنوع غذا')),
                ('packaging', models.IntegerField(blank=True, choices=[(5, 'عالی'), (4, 'خوب'), (3, 'متوسط'), (2, 'ضعیف'), (1, 'بسیار ضعیف')], help_text='کیفیت بسته\u200cبندی و ظروف', null=True, verbose_name='بسته\u200cبندی')),
                ('service_quality', models.IntegerField(blank=True, choices=[(5, 'عالی'), (4, 'خوب'), (3, 'متوسط'), (2, 'ضعیف'), (1, 'بسیار ضعیف')], help_text='نحوه سرو و برخورد پرسنل', null=True, verbose_name='کیفیت سرویس')),
                ('comments', models.TextField(blank=True, help_text='نظرات، پیشنهادات یا انتقادات شما', null=True, verbose_name='نظرات و پیشنهادات')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='آدرس IP کاربر در زمان ارسال', null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_reviewed', models.BooleanField(db_index=True, default=False, verbose_name='بررسی شده')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('admin_notes', models.TextField(blank=True, help_text='یادداشت\u200cهای داخلی برای ادمین', null=True, verbose_name='یادداشت ادمین')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meal_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='بررسی شده توسط')),
            ],
            options={
                'verbose_name': 'بازخورد غذای پرواز',
                'verbose_name_plural': 'بازخوردهای غذای پرواز',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['flight_number', 'submitted_at'], name='customer_se_flight__99c5c0_idx'), models.Index(fields=['submitted_at'], name='customer_se_submitt_7178c5_idx'), models.Index(fields=['is_reviewed', 'submitted_at'], name='customer_se_is_revi_848309_idx')],
            },
        ),
    ]
