"""
Constants for support app
"""
from django.db import models
from django.utils.translation import gettext_lazy as _


# Ticket Status Choices
TICKET_STATUS_OPEN = 'OPEN'
TICKET_STATUS_IN_PROGRESS = 'IN_PROGRESS'
TICKET_STATUS_WAITING_CUSTOMER = 'WAITING_CUSTOMER'
TICKET_STATUS_RESOLVED = 'RESOLVED'
TICKET_STATUS_CLOSED = 'CLOSED'
TICKET_STATUS_CANCELLED = 'CANCELLED'

TICKET_STATUS_CHOICES = [
    (TICKET_STATUS_OPEN, _('باز')),
    (TICKET_STATUS_IN_PROGRESS, _('در حال بررسی')),
    (TICKET_STATUS_WAITING_CUSTOMER, _('در انتظار پاسخ مشتری')),
    (TICKET_STATUS_RESOLVED, _('حل شده')),
    (TICKET_STATUS_CLOSED, _('بسته شده')),
    (TICKET_STATUS_CANCELLED, _('لغو شده')),
]


# Ticket Priority Choices
TICKET_PRIORITY_LOW = 'LOW'
TICKET_PRIORITY_NORMAL = 'NORMAL'
TICKET_PRIORITY_HIGH = 'HIGH'
TICKET_PRIORITY_URGENT = 'URGENT'
TICKET_PRIORITY_CRITICAL = 'CRITICAL'

TICKET_PRIORITY_CHOICES = [
    (TICKET_PRIORITY_LOW, _('کم')),
    (TICKET_PRIORITY_NORMAL, _('عادی')),
    (TICKET_PRIORITY_HIGH, _('بالا')),
    (TICKET_PRIORITY_URGENT, _('فوری')),
    (TICKET_PRIORITY_CRITICAL, _('بحرانی')),
]


# Ticket Category Choices
TICKET_CATEGORY_BOOKING = 'BOOKING'
TICKET_CATEGORY_FLIGHT = 'FLIGHT'
TICKET_CATEGORY_PAYMENT = 'PAYMENT'
TICKET_CATEGORY_REFUND = 'REFUND'
TICKET_CATEGORY_CANCELLATION = 'CANCELLATION'
TICKET_CATEGORY_BAGGAGE = 'BAGGAGE'
TICKET_CATEGORY_CHECK_IN = 'CHECK_IN'
TICKET_CATEGORY_LOYALTY = 'LOYALTY'
TICKET_CATEGORY_TECHNICAL = 'TECHNICAL'
TICKET_CATEGORY_HR = 'HR'  # همکاری با ما - منابع انسانی
TICKET_CATEGORY_FEEDBACK = 'FEEDBACK'  # انتقادات و پیشنهادات - روابط عمومی
TICKET_CATEGORY_MISC = 'MISC'  # متفرقه
TICKET_CATEGORY_SECURITY = 'SECURITY'  # ارتباط با حراست
TICKET_CATEGORY_OTHER = 'OTHER'

TICKET_CATEGORY_CHOICES = [
    (TICKET_CATEGORY_BOOKING, _('رزرو بلیط')),
    (TICKET_CATEGORY_FLIGHT, _('پرواز')),
    (TICKET_CATEGORY_PAYMENT, _('پرداخت')),
    (TICKET_CATEGORY_REFUND, _('استرداد')),
    (TICKET_CATEGORY_CANCELLATION, _('لغو پرواز')),
    (TICKET_CATEGORY_BAGGAGE, _('بار و چمدان')),
    (TICKET_CATEGORY_CHECK_IN, _('چک این')),
    (TICKET_CATEGORY_LOYALTY, _('برنامه وفاداری')),
    (TICKET_CATEGORY_TECHNICAL, _('مشکل فنی')),
    (TICKET_CATEGORY_HR, _('همکاری با ما')),
    (TICKET_CATEGORY_FEEDBACK, _('انتقادات و پیشنهادات')),
    (TICKET_CATEGORY_MISC, _('متفرقه')),
    (TICKET_CATEGORY_SECURITY, _('ارتباط با حراست')),
    (TICKET_CATEGORY_OTHER, _('سایر')),
]


# Ticket Source Choices
TICKET_SOURCE_WEB = 'WEB'
TICKET_SOURCE_MOBILE = 'MOBILE'
TICKET_SOURCE_PHONE = 'PHONE'
TICKET_SOURCE_EMAIL = 'EMAIL'
TICKET_SOURCE_CHAT = 'CHAT'
TICKET_SOURCE_SOCIAL = 'SOCIAL'
TICKET_SOURCE_NIRA = 'NIRA'  # Integration with Nira system
TICKET_SOURCE_OTHER = 'OTHER'

TICKET_SOURCE_CHOICES = [
    (TICKET_SOURCE_WEB, _('وب سایت')),
    (TICKET_SOURCE_MOBILE, _('موبایل')),
    (TICKET_SOURCE_PHONE, _('تلفن')),
    (TICKET_SOURCE_EMAIL, _('ایمیل')),
    (TICKET_SOURCE_CHAT, _('چت آنلاین')),
    (TICKET_SOURCE_SOCIAL, _('شبکه‌های اجتماعی')),
    (TICKET_SOURCE_NIRA, _('سیستم نیرا')),
    (TICKET_SOURCE_OTHER, _('سایر')),
]


# Message Type Choices
MESSAGE_TYPE_CUSTOMER = 'CUSTOMER'
MESSAGE_TYPE_STAFF = 'STAFF'
MESSAGE_TYPE_SYSTEM = 'SYSTEM'
MESSAGE_TYPE_NIRA = 'NIRA'  # Messages from Nira system

MESSAGE_TYPE_CHOICES = [
    (MESSAGE_TYPE_CUSTOMER, _('مشتری')),
    (MESSAGE_TYPE_STAFF, _('پرسنل')),
    (MESSAGE_TYPE_SYSTEM, _('سیستم')),
    (MESSAGE_TYPE_NIRA, _('سیستم نیرا')),
]


# Attachment Type Choices
ATTACHMENT_TYPE_IMAGE = 'IMAGE'
ATTACHMENT_TYPE_DOCUMENT = 'DOCUMENT'
ATTACHMENT_TYPE_PDF = 'PDF'
ATTACHMENT_TYPE_OTHER = 'OTHER'

ATTACHMENT_TYPE_CHOICES = [
    (ATTACHMENT_TYPE_IMAGE, _('تصویر')),
    (ATTACHMENT_TYPE_DOCUMENT, _('سند')),
    (ATTACHMENT_TYPE_PDF, _('PDF')),
    (ATTACHMENT_TYPE_OTHER, _('سایر')),
]

