# Generated by Django 4.2.2 on 2026-02-16 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('TIER', 'مشتریان باشگاه (برنزی/نقره\u200cای/طلایی)'), ('CUSTOM', 'شماره\u200cهای دلخواه')], max_length=10, verbose_name='نوع گیرندگان')),
                ('tiers', models.JSONField(blank=True, default=list, help_text='مثلاً ["BRONZE","SILVER","GOLD"]', verbose_name='سطح\u200cهای عضویت')),
                ('custom_numbers_raw', models.TextField(blank=True, help_text='شماره\u200cها را با کاما یا خط جدید جدا کنید', verbose_name='شماره\u200cهای دلخواه')),
                ('message', models.TextField(verbose_name='متن پیامک')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SENT', 'ارسال شد'), ('PARTIAL', 'ارسال جزئی'), ('FAILED', 'ناموفق')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ارسال شده')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='تعداد کل گیرندگان')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='ارسال توسط')),
            ],
            options={
                'verbose_name': 'لاگ پیامک',
                'verbose_name_plural': 'لاگ\u200cهای پیامک',
                'ordering': ['-created_at'],
            },
        ),
    ]
