"""
Constants and choices for flights app
"""

# Flight Status
FLIGHT_SCHEDULED = 'SCHEDULED'
FLIGHT_DELAYED = 'DELAYED'
FLIGHT_CANCELLED = 'CANCELLED'
FLIGHT_COMPLETED = 'COMPLETED'
FLIGHT_BOARDING = 'BOARDING'
FLIGHT_DEPARTED = 'DEPARTED'
FLIGHT_ARRIVED = 'ARRIVED'

FLIGHT_STATUS_CHOICES = [
    (FLIGHT_SCHEDULED, 'برنامه‌ریزی شده'),
    (FLIGHT_DELAYED, 'تأخیر'),
    (FLIGHT_CANCELLED, 'لغو شده'),
    (FLIGHT_COMPLETED, 'تکمیل شده'),
    (FLIGHT_BOARDING, 'در حال سوار شدن'),
    (FLIGHT_DEPARTED, 'پرواز کرده'),
    (FLIGHT_ARRIVED, 'فرود آمده'),
]

# Cabin Classes
CABIN_ECONOMY = 'ECONOMY'
CABIN_BUSINESS = 'BUSINESS'
CABIN_FIRST_CLASS = 'FIRST_CLASS'
CABIN_PREMIUM_ECONOMY = 'PREMIUM_ECONOMY'

CABIN_CLASS_CHOICES = [
    (CABIN_ECONOMY, 'اکونومی'),
    (CABIN_BUSINESS, 'بیزینس'),
    (CABIN_FIRST_CLASS, 'فرست کلاس'),
    (CABIN_PREMIUM_ECONOMY, 'اکونومی پریمیوم'),
]

# Aircraft Types
AIRCRAFT_TYPE_NARROW_BODY = 'NARROW_BODY'
AIRCRAFT_TYPE_WIDE_BODY = 'WIDE_BODY'
AIRCRAFT_TYPE_REGIONAL = 'REGIONAL'

AIRCRAFT_TYPE_CHOICES = [
    (AIRCRAFT_TYPE_NARROW_BODY, 'بدنه باریک'),
    (AIRCRAFT_TYPE_WIDE_BODY, 'بدنه پهن'),
    (AIRCRAFT_TYPE_REGIONAL, 'منطقه‌ای'),
]

# Flight Types
FLIGHT_TYPE_DIRECT = 'DIRECT'
FLIGHT_TYPE_NON_STOP = 'NON_STOP'
FLIGHT_TYPE_ONE_STOP = 'ONE_STOP'
FLIGHT_TYPE_MULTI_STOP = 'MULTI_STOP'

FLIGHT_TYPE_CHOICES = [
    (FLIGHT_TYPE_DIRECT, 'مستقیم'),
    (FLIGHT_TYPE_NON_STOP, 'بدون توقف'),
    (FLIGHT_TYPE_ONE_STOP, 'یک توقف'),
    (FLIGHT_TYPE_MULTI_STOP, 'چند توقف'),
]

# Time of Day
TIME_MORNING = 'MORNING'  # 6:00 - 12:00
TIME_AFTERNOON = 'AFTERNOON'  # 12:00 - 18:00
TIME_EVENING = 'EVENING'  # 18:00 - 22:00
TIME_NIGHT = 'NIGHT'  # 22:00 - 6:00

TIME_OF_DAY_CHOICES = [
    (TIME_MORNING, 'صبح'),
    (TIME_AFTERNOON, 'بعد از ظهر'),
    (TIME_EVENING, 'عصر'),
    (TIME_NIGHT, 'شب'),
]

# Price Change Factors
PRICE_FACTOR_DEMAND = 'DEMAND'
PRICE_FACTOR_TIME = 'TIME'
PRICE_FACTOR_SEASON = 'SEASON'
PRICE_FACTOR_COMPETITION = 'COMPETITION'
PRICE_FACTOR_LOAD = 'LOAD'

PRICE_FACTORS = [
    (PRICE_FACTOR_DEMAND, 'تقاضا'),
    (PRICE_FACTOR_TIME, 'زمان'),
    (PRICE_FACTOR_SEASON, 'فصل'),
    (PRICE_FACTOR_COMPETITION, 'رقابت'),
    (PRICE_FACTOR_LOAD, 'بارگیری'),
]

# Seat Types
SEAT_TYPE_REGULAR = 'REGULAR'
SEAT_TYPE_EXTRA_LEGROOM = 'EXTRA_LEGROOM'
SEAT_TYPE_WINDOW = 'WINDOW'
SEAT_TYPE_AISLE = 'AISLE'
SEAT_TYPE_MIDDLE = 'MIDDLE'

SEAT_TYPE_CHOICES = [
    (SEAT_TYPE_REGULAR, 'عادی'),
    (SEAT_TYPE_EXTRA_LEGROOM, 'فضای بیشتر برای پا'),
    (SEAT_TYPE_WINDOW, 'پنجره'),
    (SEAT_TYPE_AISLE, 'راهرو'),
    (SEAT_TYPE_MIDDLE, 'وسط'),
]

# Default Values
DEFAULT_FLIGHT_STATUS = FLIGHT_SCHEDULED
DEFAULT_CABIN_CLASS = CABIN_ECONOMY
MIN_FLIGHT_DURATION_MINUTES = 30
MAX_FLIGHT_DURATION_HOURS = 24

