"""
Constants for customer_service app
"""
from django.utils.translation import gettext_lazy as _


# Customer Tier Levels
CUSTOMER_TIER_GOLD = 'GOLD'
CUSTOMER_TIER_SILVER = 'SILVER'
CUSTOMER_TIER_BRONZE = 'BRONZE'

CUSTOMER_TIER_CHOICES = [
    (CUSTOMER_TIER_GOLD, _('طلا')),
    (CUSTOMER_TIER_SILVER, _('نقره')),
    (CUSTOMER_TIER_BRONZE, _('برنز')),
]

# Tier Calculation Criteria Types
CRITERIA_TYPE_TOTAL_PURCHASE_AMOUNT = 'TOTAL_PURCHASE_AMOUNT'
CRITERIA_TYPE_TOTAL_BOOKINGS_COUNT = 'TOTAL_BOOKINGS_COUNT'
CRITERIA_TYPE_MONTHLY_PURCHASE_AMOUNT = 'MONTHLY_PURCHASE_AMOUNT'
CRITERIA_TYPE_DAYS_SINCE_REGISTRATION = 'DAYS_SINCE_REGISTRATION'
CRITERIA_TYPE_LAST_PURCHASE_DAYS = 'LAST_PURCHASE_DAYS'

CRITERIA_TYPE_CHOICES = [
    (CRITERIA_TYPE_TOTAL_PURCHASE_AMOUNT, _('مبلغ کل خرید')),
    (CRITERIA_TYPE_TOTAL_BOOKINGS_COUNT, _('تعداد کل رزروها')),
    (CRITERIA_TYPE_MONTHLY_PURCHASE_AMOUNT, _('مبلغ خرید ماهانه')),
    (CRITERIA_TYPE_DAYS_SINCE_REGISTRATION, _('روز از زمان ثبت‌نام')),
    (CRITERIA_TYPE_LAST_PURCHASE_DAYS, _('روز از آخرین خرید')),
]

# Comparison Operators
OPERATOR_GREATER_THAN = 'GT'
OPERATOR_GREATER_THAN_OR_EQUAL = 'GTE'
OPERATOR_LESS_THAN = 'LT'
OPERATOR_LESS_THAN_OR_EQUAL = 'LTE'
OPERATOR_EQUAL = 'EQ'

OPERATOR_CHOICES = [
    (OPERATOR_GREATER_THAN, _('بزرگتر از')),
    (OPERATOR_GREATER_THAN_OR_EQUAL, _('بزرگتر یا مساوی با')),
    (OPERATOR_LESS_THAN, _('کوچکتر از')),
    (OPERATOR_LESS_THAN_OR_EQUAL, _('کوچکتر یا مساوی با')),
    (OPERATOR_EQUAL, _('مساوی با')),
]

# Chat Session Status
CHAT_STATUS_OPEN = 'OPEN'
CHAT_STATUS_WAITING = 'WAITING'
CHAT_STATUS_IN_PROGRESS = 'IN_PROGRESS'
CHAT_STATUS_CLOSED = 'CLOSED'

CHAT_STATUS_CHOICES = [
    (CHAT_STATUS_OPEN, _('باز')),
    (CHAT_STATUS_WAITING, _('در انتظار')),
    (CHAT_STATUS_IN_PROGRESS, _('در حال بررسی')),
    (CHAT_STATUS_CLOSED, _('بسته شده')),
]

# Message Types
MESSAGE_TYPE_CUSTOMER = 'CUSTOMER'
MESSAGE_TYPE_STAFF = 'STAFF'
MESSAGE_TYPE_SYSTEM = 'SYSTEM'

MESSAGE_TYPE_CHOICES = [
    (MESSAGE_TYPE_CUSTOMER, _('مشتری')),
    (MESSAGE_TYPE_STAFF, _('پرسنل')),
    (MESSAGE_TYPE_SYSTEM, _('سیستم')),
]

