"""
Constants and choices for payments app
"""

# Payment Status
PAYMENT_PENDING = 'PENDING'
PAYMENT_PROCESSING = 'PROCESSING'
PAYMENT_COMPLETED = 'COMPLETED'
PAYMENT_FAILED = 'FAILED'
PAYMENT_CANCELLED = 'CANCELLED'
PAYMENT_REFUNDED = 'REFUNDED'

PAYMENT_STATUS_CHOICES = [
    (PAYMENT_PENDING, 'در انتظار'),
    (PAYMENT_PROCESSING, 'در حال پردازش'),
    (PAYMENT_COMPLETED, 'تکمیل شده'),
    (PAYMENT_FAILED, 'ناموفق'),
    (PAYMENT_CANCELLED, 'لغو شده'),
    (PAYMENT_REFUNDED, 'بازپرداخت شده'),
]

# Payment Method
PAYMENT_METHOD_ONLINE = 'ONLINE'
PAYMENT_METHOD_CARD = 'CARD'
PAYMENT_METHOD_WALLET = 'WALLET'
PAYMENT_METHOD_CRYPTO = 'CRYPTO'
PAYMENT_METHOD_INSTALLMENT = 'INSTALLMENT'
PAYMENT_METHOD_CASH = 'CASH'

PAYMENT_METHOD_CHOICES = [
    (PAYMENT_METHOD_ONLINE, 'پرداخت آنلاین'),
    (PAYMENT_METHOD_CARD, 'کارت بانکی'),
    (PAYMENT_METHOD_WALLET, 'کیف پول الکترونیکی'),
    (PAYMENT_METHOD_CRYPTO, 'ارز دیجیتال'),
    (PAYMENT_METHOD_INSTALLMENT, 'اقساطی'),
    (PAYMENT_METHOD_CASH, 'نقدی'),
]

# Payment Gateway
GATEWAY_BANK_MELI = 'BANK_MELI'
GATEWAY_BANK_PARSIAN = 'BANK_PARSIAN'
GATEWAY_BANK_MELLAT = 'BANK_MELLAT'
GATEWAY_BANK_SADERAT = 'BANK_SADERAT'
GATEWAY_BANK_TEJARAT = 'BANK_TEJARAT'
GATEWAY_PAYPAL = 'PAYPAL'
GATEWAY_STRIPE = 'STRIPE'
GATEWAY_ZARINPAL = 'ZARINPAL'
GATEWAY_NIRA = 'NIRA'

PAYMENT_GATEWAY_CHOICES = [
    (GATEWAY_BANK_MELI, 'بانک ملی'),
    (GATEWAY_BANK_PARSIAN, 'بانک پارسیان'),
    (GATEWAY_BANK_MELLAT, 'بانک ملت'),
    (GATEWAY_BANK_SADERAT, 'بانک صادرات'),
    (GATEWAY_BANK_TEJARAT, 'بانک تجارت'),
    (GATEWAY_PAYPAL, 'PayPal'),
    (GATEWAY_STRIPE, 'Stripe'),
    (GATEWAY_ZARINPAL, 'زرین‌پال'),
    (GATEWAY_NIRA, 'پرداخت نیرا (IBE)'),
]

# Transaction Type
TRANSACTION_PAYMENT = 'PAYMENT'
TRANSACTION_REFUND = 'REFUND'
TRANSACTION_PARTIAL_REFUND = 'PARTIAL_REFUND'
TRANSACTION_CHARGEBACK = 'CHARGEBACK'

TRANSACTION_TYPE_CHOICES = [
    (TRANSACTION_PAYMENT, 'پرداخت'),
    (TRANSACTION_REFUND, 'بازپرداخت'),
    (TRANSACTION_PARTIAL_REFUND, 'بازپرداخت جزئی'),
    (TRANSACTION_CHARGEBACK, 'برگشت وجه'),
]

# Installment Plans
INSTALLMENT_3_MONTHS = 3
INSTALLMENT_6_MONTHS = 6
INSTALLMENT_12_MONTHS = 12

INSTALLMENT_PLANS = [
    (INSTALLMENT_3_MONTHS, '3 ماهه'),
    (INSTALLMENT_6_MONTHS, '6 ماهه'),
    (INSTALLMENT_12_MONTHS, '12 ماهه'),
]

# Default Values
DEFAULT_PAYMENT_STATUS = PAYMENT_PENDING
DEFAULT_PAYMENT_METHOD = PAYMENT_METHOD_ONLINE

# Interest Rates (annual)
INSTALLMENT_INTEREST_RATE_3 = 0.18  # 18% annual
INSTALLMENT_INTEREST_RATE_6 = 0.20  # 20% annual
INSTALLMENT_INTEREST_RATE_12 = 0.22  # 22% annual

INSTALLMENT_INTEREST_RATES = {
    INSTALLMENT_3_MONTHS: INSTALLMENT_INTEREST_RATE_3,
    INSTALLMENT_6_MONTHS: INSTALLMENT_INTEREST_RATE_6,
    INSTALLMENT_12_MONTHS: INSTALLMENT_INTEREST_RATE_12,
}

