"""
Django settings for nasim project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-r&m1)kdaada)m%2ik%4(vwjb@2qd+y9@1h5zaw-*qmq^p3sn%@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'ckeditor',  # Rich Text Editor for SEO
    'ckeditor_uploader',  # Image upload for CKEditor
    
    # Local apps
    'authenticate',  # Auth: login, register, forgot password
    'accounts',
    'flights',
    'bookings',
    'payments',
    'notifications',
    'pilots',
    'security',
    'blog',  # Blog and SEO content management
    'gallery',  # Gallery and media management
    'support',  # Support and ticket system
    'customer_service',  # Customer service and tier management
    'sms',  # ارسال پیامک با ملی پیامک (باشگاه مشتریان و شماره‌های دلخواه)
    'main',  # اپ قبلی
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nasim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nasim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# React Frontend Build Directory
FRONTEND_BUILD_DIR = os.path.join(BASE_DIR, 'frontend', 'build')

# Additional static files directories (only if build exists)
STATICFILES_DIRS = []
if os.path.exists(FRONTEND_BUILD_DIR):
    static_dir = os.path.join(FRONTEND_BUILD_DIR, 'static')
    if os.path.exists(static_dir):
        STATICFILES_DIRS.append(static_dir)

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = 'blog/uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 400,
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks'],
        ],
        'toolbar': 'Custom',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
        'toolbarCanCollapse': True,
        'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
        'filebrowserBrowseUrl': '/ckeditor/browse/',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserImageBrowseUrl': '/ckeditor/browse/',
        'filebrowserImageUploadUrl': '/ckeditor/upload/',
    },
    'seo_optimized': {
        'toolbar': 'full',
        'height': 500,
        'width': '100%',
        'toolbar_Custom': [
            ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
            ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
            '/',
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe'],
            '/',
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks'],
            ['About'],
        ],
        'toolbar': 'Custom',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
        'toolbarCanCollapse': True,
        'extraPlugins': ','.join([
            'uploadimage',
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'codesnippet',
        ]),
        'codeSnippet_theme': 'monokai_sublime',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserImageBrowseUrl': '/ckeditor/browse/',
        'filebrowserImageUploadUrl': '/ckeditor/upload/',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev server
    "http://127.0.0.1:3000",  # React dev server
    "http://localhost:8000",  # Django served frontend
    "http://127.0.0.1:8000",  # Django served frontend
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@nasimair.com')

# Support Email Mapping (هر دسته‌بندی به یک ایمیل مشخص)
SUPPORT_EMAIL_MAPPING = {
    'HR': os.environ.get('SUPPORT_EMAIL_HR', 'grifindorekamyar@gmail.com'),  # همکاری با ما
    'FEEDBACK': os.environ.get('SUPPORT_EMAIL_FEEDBACK', 'gryffyndorkamyar@gmail.com'),  # انتقادات و پیشنهادات
    'MISC': os.environ.get('SUPPORT_EMAIL_MISC', 'gryffyndorekamyar@gmail.com'),  # متفرقه
    # سایر دسته‌بندی‌ها به این ایمیل می‌روند (اختیاری)
    'DEFAULT': os.environ.get('SUPPORT_EMAIL_DEFAULT', 'support@nasimair.com'),
}

# Security Contact Information (حراست)
SECURITY_CONTACT_PHONE = os.environ.get('SECURITY_CONTACT_PHONE', '021123456789')

# WhatsApp Configuration (برای اعلان‌های چت)
# برای استفاده از واتساپ، باید API key و URL سرویس واتساپ خود را تنظیم کنید
# می‌توانید از سرویس‌های مختلف مثل Twilio، کاوه نگار، پیامک گستر و غیره استفاده کنید
WHATSAPP_API_URL = os.environ.get('WHATSAPP_API_URL', '')  # URL API واتساپ
WHATSAPP_API_KEY = os.environ.get('WHATSAPP_API_KEY', '')  # API Key
WHATSAPP_PHONE_ID = os.environ.get('WHATSAPP_PHONE_ID', '')  # Phone ID (برای Twilio)
ADMIN_WHATSAPP_NUMBER = os.environ.get('ADMIN_WHATSAPP_NUMBER', '+989379146130')  # شماره واتساپ ادمین (مثال: +989123456789)

# Telegram Bot Configuration (برای اعلان پیام‌های جدید چت)
# برای دریافت chat_id: به ربات خود در تلگرام /start بفرستید، سپس به آدرس زیر بروید:
# https://api.telegram.org/bot<TOKEN>/getUpdates و chat.id را از پاسخ کپی کنید
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '')
ADMIN_BASE_URL = os.environ.get('ADMIN_BASE_URL', 'http://127.0.0.1:8000')  # آدرس پایه پنل ادمین (در production تغییر دهید)
# پروکسی برای تلگرام (اختیاری - اگر api.telegram.org در دسترس نیست، مثلاً: http://127.0.0.1:1080)
TELEGRAM_PROXY = os.environ.get('TELEGRAM_PROXY', '')

# تنظیمات ملی پیامک (MelliPayamak / Payamak-Panel) برای ارسال پیامک
# از پنل ادمین می‌توان به مشتریان برنزی/نقره‌ای/طلایی و شماره‌های دلخواه پیامک ارسال کرد
MELLIPAYAMAK_USERNAME = os.environ.get('MELLIPAYAMAK_USERNAME', '')
MELLIPAYAMAK_PASSWORD = os.environ.get('MELLIPAYAMAK_PASSWORD', '')
MELLIPAYAMAK_FROM_NUMBER = os.environ.get('MELLIPAYAMAK_FROM_NUMBER', '')  # شماره خط فرستنده (مثال: 3000xxxx یا 5000xxxx)

# تنظیمات API نیرا (Nira) برای سیستم فروش اینترنتی
# این مقادیر را در فایل .env تنظیم کنید
NIRA_BASE_URL = os.environ.get('NIRA_BASE_URL', '')  # URL پایه سیستم نیرا (مثال: https://airline.example.com)
NIRA_OFFICE_USER = os.environ.get('NIRA_OFFICE_USER', '')  # نام کاربری Office برای دسترسی به Web Service
NIRA_OFFICE_PASS = os.environ.get('NIRA_OFFICE_PASS', '')  # رمز عبور Office
NIRA_API_TIMEOUT = int(os.environ.get('NIRA_API_TIMEOUT', '60'))  # Timeout برای درخواست‌های API (ثانیه) - افزایش یافت به 60

# تنظیمات API برای دریافت اطلاعات لحظه‌ای پروازها
# این API ها برای دریافت زمان واقعی، تأخیر، گیت و تعداد توقف استفاده می‌شوند
# وقتی API Key ها آماده شدند، فقط باید در فایل .env تنظیم شوند

# سازمان هواپیمایی کشوری (CAO)
CAO_API_URL = os.environ.get('CAO_API_URL', '')  # URL API سازمان هواپیمایی کشوری
CAO_API_KEY = os.environ.get('CAO_API_KEY', '')  # API Key سازمان هواپیمایی کشوری

# فرودگاه‌ها (امام خمینی، مهرآباد و غیره)
AIRPORT_API_URL = os.environ.get('AIRPORT_API_URL', '')  # URL API فرودگاه‌ها
AIRPORT_API_KEY = os.environ.get('AIRPORT_API_KEY', '')  # API Key فرودگاه‌ها

# سرویس‌های بین‌المللی (برای پروازهای خارجی - اختیاری)
FLIGHTAWARE_API_KEY = os.environ.get('FLIGHTAWARE_API_KEY', '')  # API Key FlightAware (برای پروازهای بین‌المللی)
AVIATIONSTACK_API_KEY = os.environ.get('AVIATIONSTACK_API_KEY', '')  # API Key AviationStack (برای پروازهای بین‌المللی)

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-csrf-token',
]

# Allow all origins in development (for testing)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Redis Cache Configuration (برای استفاده در آینده)
# موقتاً غیرفعال شده تا زمانی که django-redis نصب شود
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }

# Session Configuration (موقتاً به database تغییر یافت)
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_CACHE_ALIAS = 'default'
