# Generated by Django 5.2.6 on 2025-11-22 14:40

import ckeditor_uploader.fields
import django.db.models.deletion
import gallery.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(help_text='اسلاگ یکتا برای URL', max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, help_text='تصویر نماینده دسته\u200cبندی', null=True, upload_to='gallery/categories/', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال')], db_index=True, default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان برای SEO', max_length=60, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, help_text='توضیحات برای SEO', max_length=160, null=True, verbose_name='توضیحات متا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی گالری',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای گالری',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug', 'status'], name='gallery_gal_slug_f705e2_idx'), models.Index(fields=['status', 'order'], name='gallery_gal_status_b36b10_idx'), models.Index(fields=['is_featured', 'status'], name='gallery_gal_is_feat_f73bd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='اسلاگ یکتا برای URL', max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='توضیحات کامل آلبوم', null=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, help_text='تصویر نماینده آلبوم', null=True, upload_to='gallery/albums/', verbose_name='تصویر جلد')),
                ('status', models.CharField(choices=[('PUBLISHED', 'منتشر شده'), ('DRAFT', 'پیش\u200cنویس'), ('ARCHIVED', 'بایگانی شده')], db_index=True, default='PUBLISHED', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات متا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_albums', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='gallery.gallerycategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'آلبوم گالری',
                'verbose_name_plural': 'آلبوم\u200cهای گالری',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='اسلاگ یکتا برای URL', max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='توضیحات کامل تصویر', null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(help_text='تصویر اصلی (حداکثر 10MB)', upload_to='gallery/images/', validators=[gallery.validators.validate_image_size, gallery.validators.validate_image_format], verbose_name='تصویر')),
                ('thumbnail', models.ImageField(blank=True, help_text='تصویر کوچک (خودکار تولید می\u200cشود)', null=True, upload_to='gallery/thumbnails/', verbose_name='تصویر کوچک')),
                ('media_type', models.CharField(choices=[('IMAGE', 'تصویر'), ('VIDEO', 'ویدیو'), ('DOCUMENT', 'سند')], db_index=True, default='IMAGE', max_length=20, verbose_name='نوع رسانه')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='حجم فایل به بایت', verbose_name='حجم فایل (بایت)')),
                ('width', models.PositiveIntegerField(default=0, help_text='عرض تصویر به پیکسل', verbose_name='عرض')),
                ('height', models.PositiveIntegerField(default=0, help_text='ارتفاع تصویر به پیکسل', verbose_name='ارتفاع')),
                ('status', models.CharField(choices=[('PUBLISHED', 'منتشر شده'), ('DRAFT', 'پیش\u200cنویس'), ('ARCHIVED', 'بایگانی شده')], db_index=True, default='PUBLISHED', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='ثابت')),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید')),
                ('download_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد دانلود')),
                ('alt_text', models.CharField(blank=True, help_text='متن جایگزین برای SEO و دسترسی\u200cپذیری', max_length=200, null=True, verbose_name='متن جایگزین')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات متا')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی به صورت JSON', verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ انتشار')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gallery.galleryalbum', verbose_name='آلبوم')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gallery.gallerycategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['slug', 'status'], name='gallery_gal_slug_ae8607_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['status', 'published_at'], name='gallery_gal_status_65832d_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['category', 'status'], name='gallery_gal_categor_9ce41f_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['author', 'status'], name='gallery_gal_author__d1658e_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['is_featured', 'status'], name='gallery_gal_is_feat_214546_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['slug', 'status'], name='gallery_gal_slug_a93dad_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['status', 'published_at'], name='gallery_gal_status_3f36b2_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['category', 'status'], name='gallery_gal_categor_b365dc_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['album', 'status'], name='gallery_gal_album_i_96f909_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['author', 'status'], name='gallery_gal_author__c6cb1f_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['is_featured', 'status'], name='gallery_gal_is_feat_0dadf4_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['media_type', 'status'], name='gallery_gal_media_t_ff74f8_idx'),
        ),
    ]
