# Generated by Django 4.2.2 on 2025-11-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='ترتیب نمایش در آلبوم', verbose_name='ترتیب نمایش'),
        ),
    ]
