# Generated by Django 4.2.2 on 2026-02-01 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0002_galleryimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('title', models.CharField(help_text='عنوان توضیحی برای تصویر', max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(help_text='تصویر اصلی اسلایدر (حداکثر 10MB، توصیه می\u200cشود: 1920x1080)', upload_to='hero_slider/', validators=[gallery.validators.validate_image_size, gallery.validators.validate_image_format], verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, help_text='متن جایگزین برای SEO و دسترسی\u200cپذیری', max_length=200, null=True, verbose_name='متن جایگزین')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='ترتیب نمایش در اسلایدر (عدد کمتر = اولویت بیشتر)', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='فعال/غیرفعال بودن تصویر در اسلایدر', verbose_name='فعال')),
                ('link_url', models.URLField(blank=True, help_text='لینک اختیاری برای هدایت کاربر پس از کلیک', null=True, verbose_name='لینک')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_sliders', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدرهای صفحه اصلی',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='gallery_her_is_acti_8fe7f0_idx'), models.Index(fields=['order', 'created_at'], name='gallery_her_order_3259c4_idx')],
            },
        ),
    ]
