# Generated by Django 4.2.2 on 2026-02-16 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_heroslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('section_type', models.CharField(choices=[('SPECIAL_SERVICE', 'خدمات ویژه'), ('EXPERIENCE', 'پرواز با هواپیمایی نسیم')], db_index=True, max_length=20, unique=True, verbose_name='نوع بخش')),
                ('title1_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان خط ۱ (فارسی)')),
                ('title1_ar', models.CharField(blank=True, max_length=300, verbose_name='عنوان خط ۱ (عربی)')),
                ('title1_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان خط ۱ (انگلیسی)')),
                ('title2_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان خط ۲ (فارسی)')),
                ('title2_ar', models.CharField(blank=True, max_length=300, verbose_name='عنوان خط ۲ (عربی)')),
                ('title2_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان خط ۲ (انگلیسی)')),
                ('title3_fa', models.CharField(blank=True, max_length=300, verbose_name='عنوان خط ۳ (فارسی)')),
                ('title3_ar', models.CharField(blank=True, max_length=300, verbose_name='عنوان خط ۳ (عربی)')),
                ('title3_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان خط ۳ (انگلیسی)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات عنوان بخش صفحه اصلی',
                'verbose_name_plural': 'تنظیمات عناوین بخش صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='HomePageSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('section_type', models.CharField(choices=[('SPECIAL_SERVICE', 'خدمات ویژه'), ('EXPERIENCE', 'پرواز با هواپیمایی نسیم')], db_index=True, help_text='SPECIAL_SERVICE: خدمات ویژه | EXPERIENCE: پرواز با هواپیمایی نسیم', max_length=20, verbose_name='نوع بخش')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان عربی')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان انگلیسی')),
                ('image', models.ImageField(blank=True, help_text='تصویر المان', null=True, upload_to='homepage_sections/', validators=[gallery.validators.validate_image_size, gallery.validators.validate_image_format], verbose_name='تصویر')),
                ('link_url', models.CharField(blank=True, help_text='مسیر داخلی: /tickets | لینک خارجی: https://example.com | اسکرول: #search-form | چت: chat:luggage_tracking', max_length=500, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_section_items', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'المان بخش صفحه اصلی',
                'verbose_name_plural': 'المان\u200cهای بخش صفحه اصلی',
                'ordering': ['section_type', 'order', '-created_at'],
                'indexes': [models.Index(fields=['section_type', 'is_active'], name='gallery_hom_section_6872a1_idx'), models.Index(fields=['order', 'section_type'], name='gallery_hom_order_3f22c7_idx')],
            },
        ),
    ]
