# Generated by Django 4.2.2 on 2026-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_homepage_section_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesectionitem',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='متن / توضیح عربی'),
        ),
        migrations.AddField(
            model_name='homepagesectionitem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='متن / توضیح انگلیسی'),
        ),
        migrations.AddField(
            model_name='homepagesectionitem',
            name='description_fa',
            field=models.TextField(blank=True, help_text='متن بدنه، قیمت کارت مسیر، یا محتوای مودال FAQ', verbose_name='متن / توضیح فارسی'),
        ),
        migrations.AlterField(
            model_name='homepagesectionconfig',
            name='section_type',
            field=models.CharField(choices=[('SPECIAL_SERVICE', 'خدمات ویژه'), ('EXPERIENCE', 'پرواز با هواپیمایی نسیم'), ('HERO', 'متن هیرو (بالای صفحه)'), ('QUOTE', 'نقل\u200cقول زیر هیرو'), ('MEMBERSHIP', 'بنر عضویت'), ('SURVEY', 'بنر نظرسنجی / تصویر بزرگ'), ('FAQ', 'سوالات متداول'), ('POPULAR_ROUTES', 'مسیرهای پرطرفدار')], db_index=True, max_length=20, unique=True, verbose_name='نوع بخش'),
        ),
        migrations.AlterField(
            model_name='homepagesectionconfig',
            name='title2_ar',
            field=models.CharField(blank=True, max_length=500, verbose_name='عنوان خط ۲ (عربی)'),
        ),
        migrations.AlterField(
            model_name='homepagesectionconfig',
            name='title2_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='عنوان خط ۲ (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='homepagesectionconfig',
            name='title2_fa',
            field=models.CharField(blank=True, max_length=500, verbose_name='عنوان خط ۲ (فارسی)'),
        ),
        migrations.AlterField(
            model_name='homepagesectionitem',
            name='section_type',
            field=models.CharField(choices=[('SPECIAL_SERVICE', 'خدمات ویژه'), ('EXPERIENCE', 'پرواز با هواپیمایی نسیم'), ('HERO', 'متن هیرو (بالای صفحه)'), ('QUOTE', 'نقل\u200cقول زیر هیرو'), ('MEMBERSHIP', 'بنر عضویت'), ('SURVEY', 'بنر نظرسنجی / تصویر بزرگ'), ('FAQ', 'سوالات متداول'), ('POPULAR_ROUTES', 'مسیرهای پرطرفدار')], db_index=True, help_text='SPECIAL_SERVICE / EXPERIENCE / SURVEY (تصویر بنر) / FAQ / POPULAR_ROUTES', max_length=20, verbose_name='نوع بخش'),
        ),
    ]
