# Generated by Django 4.2.2 on 2025-11-18 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pilots.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(db_index=True, max_length=20, unique=True, validators=[pilots.validators.validate_license_number], verbose_name='شماره مجوز')),
                ('license_type', models.CharField(choices=[('COMMERCIAL', 'تجاری'), ('AIRLINE', 'خطوط هوایی'), ('INSTRUCTOR', 'مربی')], max_length=20, verbose_name='نوع مجوز')),
                ('license_expiry', models.DateField(verbose_name='تاریخ انقضای مجوز')),
                ('total_flight_hours', models.IntegerField(default=0, validators=[pilots.validators.validate_flight_hours], verbose_name='کل ساعات پرواز')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('ON_LEAVE', 'مرخصی'), ('SUSPENDED', 'معلق')], db_index=True, default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('aircraft_types_certified', models.JSONField(blank=True, default=list, verbose_name='انواع هواپیماهای مجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خلبان',
                'verbose_name_plural': 'خلبانان',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PilotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('SCHEDULE_CHANGE', 'تغییر برنامه پروازی'), ('FLIGHT_SWAP', 'تعویض پرواز'), ('LEAVE', 'مرخصی'), ('ROUTE_CHANGE', 'تغییر مسیر پرواز'), ('DELAY', 'تأخیر'), ('CANCELLATION', 'لغو پرواز')], max_length=20, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('CANCELLED', 'لغو شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('requested_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ درخواست شده')),
                ('response', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_requests', to='flights.flight', verbose_name='پرواز')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pilots.pilot', verbose_name='خلبان')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_request_responses', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ\u200cدهنده')),
            ],
            options={
                'verbose_name': 'درخواست خلبان',
                'verbose_name_plural': 'درخواست\u200cهای خلبانان',
                'ordering': ['-created_at'],
            },
        ),
    ]
