# Generated by Django 5.2.6 on 2025-11-22 11:54

import pilots.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddField(
            model_name='pilotrequest',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='total_flight_hours',
            field=models.PositiveIntegerField(default=0, validators=[pilots.validators.validate_flight_hours], verbose_name='کل ساعات پرواز'),
        ),
    ]
