# Generated by Django 4.2.2 on 2025-11-18 15:35

import accounts.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, validators=[accounts.validators.validate_iranian_phone_number], verbose_name='شماره تلفن')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='ملیت')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.validate_passport_number], verbose_name='شماره گذرنامه')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای گذرنامه')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, validators=[accounts.validators.validate_national_id], verbose_name='کد ملی')),
                ('loyalty_points', models.IntegerField(db_index=True, default=0, validators=[accounts.validators.validate_loyalty_points], verbose_name='امتیاز وفاداری')),
                ('membership_level', models.CharField(choices=[('BRONZE', 'برنزی'), ('SILVER', 'نقره\u200cای'), ('GOLD', 'طلایی'), ('PLATINUM', 'پلاتینیوم')], db_index=True, default='BRONZE', max_length=20, verbose_name='سطح عضویت')),
                ('preferred_seat', models.CharField(blank=True, choices=[('WINDOW', 'پنجره'), ('AISLE', 'راهرو'), ('MIDDLE', 'وسط'), ('ANY', 'هر کدام')], max_length=10, null=True, verbose_name='ترجیح صندلی')),
                ('preferred_meal', models.CharField(blank=True, choices=[('VEGETARIAN', 'گیاه\u200cخواری'), ('VEGAN', 'وگان'), ('HALAL', 'حلال'), ('KOSHER', 'کوشر'), ('REGULAR', 'عادی'), ('ANY', 'هر کدام')], max_length=50, null=True, verbose_name='ترجیح وعده غذایی')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='احراز هویت دو مرحله\u200cای فعال')),
                ('two_factor_method', models.CharField(blank=True, choices=[('SMS', 'پیامک'), ('EMAIL', 'ایمیل'), ('APP', 'اپلیکیشن احراز هویت')], max_length=20, null=True, verbose_name='روش احراز هویت دو مرحله\u200cای')),
                ('two_factor_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز احراز هویت دو مرحله\u200cای')),
                ('account_status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('SUSPENDED', 'معلق'), ('DELETED', 'حذف شده')], db_index=True, default='ACTIVE', max_length=20, verbose_name='وضعیت حساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('username', models.CharField(blank=True, help_text='اختیاری. اگر خالی باشد، از ایمیل استفاده می\u200cشود.', max_length=150, null=True, unique=True, verbose_name='نام کاربری')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'), models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'), models.Index(fields=['membership_level', 'loyalty_points'], name='accounts_us_members_8a7a09_idx'), models.Index(fields=['account_status', 'is_active'], name='accounts_us_account_387288_idx')],
            },
        ),
    ]
