# Generated by Django 4.2.2 on 2025-11-22 11:30

import uuid
from django.db import migrations, models


def generate_uuids_for_existing_users(apps, schema_editor):
    """
    Generate UUIDs for existing users
    """
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if not user.uuid:
            user.uuid = uuid.uuid4()
            user.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Step 1: Add uuid field with null=True
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(
                default=None,
                editable=False,
                null=True,
                unique=False,
                db_index=True,
                verbose_name='شناسه یکتا'
            ),
        ),
        # Step 2: Generate UUIDs for existing users
        migrations.RunPython(
            generate_uuids_for_existing_users,
            reverse_code=migrations.RunPython.noop
        ),
        # Step 3: Make uuid field NOT NULL and UNIQUE
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                db_index=True,
                verbose_name='شناسه یکتا'
            ),
        ),
    ]
