# Generated by Django 5.2.6 on 2025-11-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_uuid_to_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی آخرین ورود'),
        ),
        migrations.AddField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی به صورت JSON', verbose_name='اطلاعات اضافی'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='ترجیحات و تنظیمات کاربر به صورت JSON', verbose_name='ترجیحات کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='آی\u200cپی ثبت\u200cنام'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uuid'], name='accounts_us_uuid_8355c5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['registration_ip'], name='accounts_us_registr_c11d06_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at', 'account_status'], name='accounts_us_created_56b886_idx'),
        ),
    ]
