# Generated by Django 4.2.2 on 2026-02-11 17:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wallet_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tier', models.CharField(choices=[('BRONZE', 'برنزی'), ('SILVER', 'نقره\u200cای'), ('GOLD', 'طلایی'), ('PLATINUM', 'پلاتینیوم')], db_index=True, max_length=20, unique=True, verbose_name='سطح عضویت')),
                ('name_fa', models.CharField(default='', max_length=50, verbose_name='نام فارسی')),
                ('name_en', models.CharField(default='', max_length=50, verbose_name='نام انگلیسی')),
                ('min_bookings_total', models.IntegerField(default=0, help_text='حداقل تعداد رزروهای کامل شده (0 = غیرفعال)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل تعداد رزرو (کل)')),
                ('min_bookings_per_month', models.IntegerField(default=0, help_text='حداقل تعداد رزرو در یک ماه (0 = غیرفعال)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل رزرو در ماه')),
                ('min_bookings_per_week', models.IntegerField(default=0, help_text='حداقل تعداد رزرو در یک هفته (0 = غیرفعال)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل رزرو در هفته')),
                ('min_membership_days', models.IntegerField(default=0, help_text='حداقل تعداد روز از تاریخ ثبت\u200cنام (0 = غیرفعال)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل روز عضویت')),
                ('min_active_months', models.IntegerField(default=0, help_text='حداقل تعداد ماه\u200cهایی که کاربر حداقل 1 رزرو داشته (0 = غیرفعال)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل ماه فعال')),
                ('min_completed_flights', models.IntegerField(default=0, help_text='حداقل تعداد پروازهایی که کاربر انجام داده (0 = غیرفعال)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل پرواز انجام شده')),
                ('criteria_priority_1', models.CharField(choices=[('total_bookings', 'تعداد کل رزرو'), ('monthly_bookings', 'رزرو ماهانه'), ('weekly_bookings', 'رزرو هفتگی'), ('membership_duration', 'مدت عضویت'), ('active_months', 'ماه\u200cهای فعال'), ('completed_flights', 'پروازهای انجام شده')], default='total_bookings', max_length=50, verbose_name='معیار اولویت 1')),
                ('criteria_priority_2', models.CharField(blank=True, choices=[('total_bookings', 'تعداد کل رزرو'), ('monthly_bookings', 'رزرو ماهانه'), ('weekly_bookings', 'رزرو هفتگی'), ('membership_duration', 'مدت عضویت'), ('active_months', 'ماه\u200cهای فعال'), ('completed_flights', 'پروازهای انجام شده')], max_length=50, null=True, verbose_name='معیار اولویت 2')),
                ('criteria_priority_3', models.CharField(blank=True, choices=[('total_bookings', 'تعداد کل رزرو'), ('monthly_bookings', 'رزرو ماهانه'), ('weekly_bookings', 'رزرو هفتگی'), ('membership_duration', 'مدت عضویت'), ('active_months', 'ماه\u200cهای فعال'), ('completed_flights', 'پروازهای انجام شده')], max_length=50, null=True, verbose_name='معیار اولویت 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('auto_upgrade', models.BooleanField(default=True, help_text='آیا کاربران به صورت خودکار ارتقا پیدا کنند؟', verbose_name='ارتقا خودکار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سطح عضویت',
                'verbose_name_plural': 'تنظیمات سطوح عضویت',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='UserMembershipActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('total_bookings', models.IntegerField(default=0, help_text='تعداد کل رزروهای تکمیل شده', verbose_name='تعداد کل رزرو')),
                ('total_completed_flights', models.IntegerField(default=0, help_text='تعداد پروازهایی که کاربر انجام داده', verbose_name='تعداد پروازهای انجام شده')),
                ('first_booking_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اولین رزرو')),
                ('last_booking_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین رزرو')),
                ('bookings_last_7_days', models.IntegerField(default=0, verbose_name='رزرو در 7 روز اخیر')),
                ('bookings_last_30_days', models.IntegerField(default=0, verbose_name='رزرو در 30 روز اخیر')),
                ('bookings_last_90_days', models.IntegerField(default=0, verbose_name='رزرو در 90 روز اخیر')),
                ('active_months_count', models.IntegerField(default=0, help_text='تعداد ماه\u200cهایی که کاربر حداقل 1 رزرو داشته', verbose_name='تعداد ماه\u200cهای فعال')),
                ('average_bookings_per_month', models.FloatField(default=0.0, verbose_name='میانگین رزرو ماهانه')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین محاسبه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_activity', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فعالیت عضویت کاربر',
                'verbose_name_plural': 'فعالیت\u200cهای عضویت کاربران',
                'ordering': ['-total_bookings'],
                'indexes': [models.Index(fields=['user'], name='accounts_us_user_id_1465e0_idx'), models.Index(fields=['total_bookings'], name='accounts_us_total_b_28b250_idx'), models.Index(fields=['last_booking_date'], name='accounts_us_last_bo_f8fe9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MembershipUpgradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('old_tier', models.CharField(choices=[('BRONZE', 'برنزی'), ('SILVER', 'نقره\u200cای'), ('GOLD', 'طلایی'), ('PLATINUM', 'پلاتینیوم')], max_length=20, verbose_name='tier قبلی')),
                ('new_tier', models.CharField(choices=[('BRONZE', 'برنزی'), ('SILVER', 'نقره\u200cای'), ('GOLD', 'طلایی'), ('PLATINUM', 'پلاتینیوم')], max_length=20, verbose_name='tier جدید')),
                ('reason', models.TextField(blank=True, help_text='معیارهایی که باعث ارتقا شدند', verbose_name='دلیل ارتقا')),
                ('total_bookings_at_upgrade', models.IntegerField(default=0, verbose_name='تعداد رزرو')),
                ('membership_days_at_upgrade', models.IntegerField(default=0, verbose_name='روزهای عضویت')),
                ('is_automatic', models.BooleanField(default=True, help_text='آیا ارتقا به صورت خودکار انجام شده؟', verbose_name='ارتقا خودکار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارتقا')),
                ('upgraded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_upgrades_performed', to=settings.AUTH_USER_MODEL, verbose_name='ارتقا توسط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_upgrade_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ ارتقا عضویت',
                'verbose_name_plural': 'لاگ\u200cهای ارتقا عضویت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_me_user_id_2cbc2f_idx'), models.Index(fields=['new_tier', '-created_at'], name='accounts_me_new_tie_c9e741_idx')],
            },
        ),
    ]
