# Generated by Django 4.2.2 on 2026-02-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_default_tier_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='فقط کاربران با این گزینه فعال می\u200cتوانند از ورود پرسنل استفاده کنند.', verbose_name='وضعیت کارمند'),
        ),
    ]
