# Generated by Django 4.2.2 on 2025-11-23 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import support.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_booking_ip_booking_metadata_booking_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0002_remove_flight_flights_fli_origin__ac48a6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('reference', models.CharField(db_index=True, help_text='شماره یکتای تیکت (خودکار تولید می\u200cشود)', max_length=20, unique=True, validators=[support.validators.validate_ticket_reference], verbose_name='شماره تیکت')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(help_text='توضیحات کامل مشکل یا درخواست', verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('BOOKING', 'رزرو بلیط'), ('FLIGHT', 'پرواز'), ('PAYMENT', 'پرداخت'), ('REFUND', 'استرداد'), ('CANCELLATION', 'لغو پرواز'), ('BAGGAGE', 'بار و چمدان'), ('CHECK_IN', 'چک این'), ('LOYALTY', 'برنامه وفاداری'), ('TECHNICAL', 'مشکل فنی'), ('OTHER', 'سایر')], db_index=True, default='OTHER', max_length=50, verbose_name='دسته\u200cبندی')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('NORMAL', 'عادی'), ('HIGH', 'بالا'), ('URGENT', 'فوری'), ('CRITICAL', 'بحرانی')], db_index=True, default='NORMAL', max_length=20, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('OPEN', 'باز'), ('IN_PROGRESS', 'در حال بررسی'), ('WAITING_CUSTOMER', 'در انتظار پاسخ مشتری'), ('RESOLVED', 'حل شده'), ('CLOSED', 'بسته شده'), ('CANCELLED', 'لغو شده')], db_index=True, default='OPEN', max_length=20, verbose_name='وضعیت')),
                ('source', models.CharField(choices=[('WEB', 'وب سایت'), ('MOBILE', 'موبایل'), ('PHONE', 'تلفن'), ('EMAIL', 'ایمیل'), ('CHAT', 'چت آنلاین'), ('SOCIAL', 'شبکه\u200cهای اجتماعی'), ('NIRA', 'سیستم نیرا'), ('OTHER', 'سایر')], db_index=True, default='WEB', max_length=20, verbose_name='منبع')),
                ('nira_ticket_id', models.CharField(blank=True, db_index=True, help_text='شناسه تیکت در سیستم نیرا', max_length=100, null=True, unique=True, verbose_name='شناسه تیکت در نیرا')),
                ('nira_data', models.JSONField(blank=True, default=dict, help_text='اطلاعات دریافتی از سیستم نیرا', verbose_name='اطلاعات نیرا')),
                ('sla_deadline', models.DateTimeField(blank=True, db_index=True, help_text='مهلت پاسخگویی بر اساس اولویت', null=True, verbose_name='مهلت SLA')),
                ('first_response_at', models.DateTimeField(blank=True, help_text='زمان اولین پاسخ پرسنل', null=True, verbose_name='زمان اولین پاسخ')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='زمان حل شدن تیکت', null=True, verbose_name='زمان حل شدن')),
                ('closed_at', models.DateTimeField(blank=True, help_text='زمان بسته شدن تیکت', null=True, verbose_name='زمان بسته شدن')),
                ('ticket_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='آی\u200cپی ایجاد تیکت')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی به صورت JSON', verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص داده شده به')),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='bookings.booking', verbose_name='رزرو مرتبط')),
                ('related_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='flights.flight', verbose_name='پرواز مرتبط')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('message', models.TextField(help_text='متن پیام', verbose_name='پیام')),
                ('message_type', models.CharField(choices=[('CUSTOMER', 'مشتری'), ('STAFF', 'پرسنل'), ('SYSTEM', 'سیستم'), ('NIRA', 'سیستم نیرا')], db_index=True, default='CUSTOMER', max_length=20, verbose_name='نوع پیام')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده')),
                ('is_internal', models.BooleanField(default=False, help_text='اگر فعال باشد، مشتری این پیام را نمی\u200cبیند', verbose_name='داخلی')),
                ('message_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی ارسال پیام')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='تیکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی تیکت',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای تیکت',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='support_tic_slug_9f1795_idx'), models.Index(fields=['is_active', 'order'], name='support_tic_is_acti_22dd7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('file', models.FileField(help_text='حداکثر 10 مگابایت', upload_to='support/attachments/%Y/%m/%d/', validators=[support.validators.validate_file_size, support.validators.validate_file_type], verbose_name='فایل')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_size', models.PositiveIntegerField(help_text='حجم فایل به بایت', verbose_name='حجم فایل (بایت)')),
                ('file_type', models.CharField(choices=[('IMAGE', 'تصویر'), ('DOCUMENT', 'سند'), ('PDF', 'PDF'), ('OTHER', 'سایر')], default='OTHER', max_length=20, verbose_name='نوع فایل')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع MIME')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage', verbose_name='پیام')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیوست تیکت',
                'verbose_name_plural': 'پیوست\u200cهای تیکت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.ticketcategory', verbose_name='دسته\u200cبندی تیکت'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__0cd9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['user', 'created_at'], name='support_tic_user_id_6f727c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['message_type', 'is_read'], name='support_tic_message_a2d57b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['is_read', 'created_at'], name='support_tic_is_read_428490_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__d1cedd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['message', 'created_at'], name='support_tic_message_ca5a43_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['file_type'], name='support_tic_file_ty_1ac351_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reference'], name='support_tic_referen_b294cb_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'status'], name='support_tic_user_id_bbc719_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='support_tic_status_a0fe0d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category', 'status'], name='support_tic_categor_54255d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_tic_assigne_6ed26f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['source', 'status'], name='support_tic_source_fda4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sla_deadline', 'status'], name='support_tic_sla_dea_20fc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at', 'status'], name='support_tic_created_ff54c2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['nira_ticket_id'], name='support_tic_nira_ti_3119fe_idx'),
        ),
    ]
