# Generated by Django 4.2.2 on 2025-11-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('BOOKING', 'رزرو بلیط'), ('FLIGHT', 'پرواز'), ('PAYMENT', 'پرداخت'), ('REFUND', 'استرداد'), ('CANCELLATION', 'لغو پرواز'), ('BAGGAGE', 'بار و چمدان'), ('CHECK_IN', 'چک این'), ('LOYALTY', 'برنامه وفاداری'), ('TECHNICAL', 'مشکل فنی'), ('HR', 'همکاری با ما'), ('FEEDBACK', 'انتقادات و پیشنهادات'), ('MISC', 'متفرقه'), ('SECURITY', 'ارتباط با حراست'), ('OTHER', 'سایر')], db_index=True, default='OTHER', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
    ]
