# Generated by Django 4.2.2 on 2025-11-23 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_alter_ticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('guest_name', models.CharField(blank=True, help_text='نام کاربر برای مهمانان (غیر لاگین)', max_length=100, null=True, verbose_name='نام مهمان')),
                ('guest_email', models.EmailField(blank=True, help_text='ایمیل کاربر برای مهمانان (غیر لاگین)', max_length=254, null=True, verbose_name='ایمیل مهمان')),
                ('message', models.TextField(help_text='متن پیام چت', verbose_name='پیام')),
                ('is_staff', models.BooleanField(db_index=True, default=False, help_text='اگر فعال باشد، این پیام از پرسنل پشتیبانی است', verbose_name='پیام از پرسنل')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده')),
                ('message_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی ارسال پیام')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='شناسه نشست برای ردیابی چت\u200cهای مهمان', max_length=255, null=True, verbose_name='شناسه نشست')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(blank=True, help_text='اگر کاربر لاگین باشد، این فیلد پر می\u200cشود', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': 'پیام\u200cهای چت',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='support_cha_user_id_4e1494_idx'), models.Index(fields=['session_id', 'created_at'], name='support_cha_session_1d919a_idx'), models.Index(fields=['is_staff', 'is_read'], name='support_cha_is_staf_885c72_idx'), models.Index(fields=['created_at'], name='support_cha_created_419cf9_idx')],
            },
        ),
    ]
