# Generated by Django 4.2.2 on 2025-11-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='پیام\u200cهای مهمان تا زمانی که از سایت خارج نشده ذخیره می\u200cشوند. پیام\u200cهای کاربران عضو 72 ساعت ذخیره می\u200cشوند.', null=True, verbose_name='تاریخ انقضا'),
        ),
    ]
