# Generated by Django 4.2.2 on 2026-02-17 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_chatmessage_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('complaint_type', models.CharField(max_length=255, verbose_name='نوع شکایت')),
                ('complaint_subject', models.TextField(help_text='ترکیب نوع و موضوع انتخاب شده', verbose_name='موضوع شکایت')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کدملی')),
                ('mobile', models.CharField(max_length=20, verbose_name='شماره تلفن همراه مسافر')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='مبدا')),
                ('destination', models.CharField(blank=True, max_length=100, verbose_name='مقصد')),
                ('flight_date', models.CharField(blank=True, max_length=50, verbose_name='تاریخ')),
                ('ticket_number', models.CharField(blank=True, max_length=50, verbose_name='شماره بلیت')),
                ('flight_number', models.CharField(blank=True, max_length=50, verbose_name='شماره پرواز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('submission_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_forms', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فرم شکایت',
                'verbose_name_plural': 'فرم\u200cهای شکایت',
                'ordering': ['-created_at'],
            },
        ),
    ]
