# Generated by Django 4.2.2 on 2026-02-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_add_complaint_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintform',
            name='mobile',
            field=models.CharField(max_length=30, verbose_name='شماره تلفن همراه مسافر'),
        ),
        migrations.AlterField(
            model_name='complaintform',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='کدملی'),
        ),
    ]
