# Generated by Django 4.2.2 on 2026-02-18 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_extend_complaint_form_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('seat_number', models.CharField(blank=True, max_length=20, verbose_name='شماره صندلی')),
                ('age', models.CharField(blank=True, max_length=10, verbose_name='سن')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='مدرک تحصیلی')),
                ('flight_number', models.CharField(max_length=50, verbose_name='شماره پرواز')),
                ('contact_number', models.CharField(max_length=30, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('flight_route', models.CharField(blank=True, max_length=255, verbose_name='مسیر پرواز')),
                ('ticketing_website', models.CharField(blank=True, max_length=255, verbose_name='نام وبسایت تهیه بلیط یا آژانس')),
                ('trips_with_nasim', models.CharField(blank=True, choices=[('weekly', 'هفته\u200cای یکبار'), ('monthly', 'ماهی یکبار'), ('few_months', 'هر چند ماه'), ('yearly', 'سالی یکبار')], max_length=50, verbose_name='تعداد سفر با نسیم')),
                ('annual_flights', models.CharField(blank=True, choices=[('0-5', '۰-۵'), ('5-10', '۵-۱۰'), ('10-20', '۱۰-۲۰'), ('20+', 'بیشتر از ۲۰')], max_length=20, verbose_name='تعداد سفرهای هوایی در سال')),
                ('travel_purpose', models.CharField(blank=True, choices=[('work', 'کار'), ('leisure', 'تفریح'), ('education', 'تحصیل'), ('other', 'سایر')], max_length=50, verbose_name='هدف از سفر')),
                ('nasim_choice_reason', models.CharField(blank=True, choices=[('timing', 'زمانبندی مناسب'), ('services', 'خدمات مناسب'), ('cost', 'هزینه مناسب'), ('recommendation', 'پیشنهاد دیگران')], max_length=50, verbose_name='دلیل انتخاب نسیم')),
                ('station_staff_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='نحوه برخورد پرسنل ایستگاه و گیت')),
                ('cabin_hygiene_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='آراستگی و بهداشت کابین هواپیما')),
                ('seat_comfort_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='راحتی صندلی ها و کابین هواپیما')),
                ('cabin_temp_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='دمای کابین روی زمین و در طول پرواز')),
                ('attendants_service_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='نحوه برخورد و سرویس دهی مهمانداران')),
                ('attendants_appearance_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='راستگی ظاهری و یونیفرم مهمانداران')),
                ('sound_system_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='کیفیت سیستم صوتی و شیوایی بیان')),
                ('catering_quality_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='کیفیت بسته پذیرایی')),
                ('pilot_communication_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='برقراری ارتباط خلبان با مسافرین')),
                ('on_time_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='رضایتمندی از انجام به موقع پرواز')),
                ('vs_domestic_rating', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='رضایتمندی از نسیم در قیاس با شرکت\u200cهای داخلی')),
                ('recommend_nasim', models.CharField(blank=True, choices=[('yes', 'بله'), ('no', 'خیر')], max_length=10, verbose_name='پیشنهاد سفر با نسیم به سایرین')),
                ('suggestions', models.TextField(blank=True, verbose_name='پیشنهادها و انتقادها')),
                ('submission_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'فرم نظرسنجی',
                'verbose_name_plural': 'فرم\u200cهای نظرسنجی',
                'ordering': ['-created_at'],
            },
        ),
    ]
