# Generated by Django 4.2.2 on 2026-02-18 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0007_add_survey_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinSafetyReportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('reporter_name', models.CharField(max_length=100, verbose_name='نام')),
                ('reporter_family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('protect_personal_info', models.BooleanField(default=False, verbose_name='محافظت بیشتر اطلاعات شخصی')),
                ('occurrence_day', models.CharField(blank=True, max_length=2, verbose_name='روز رویداد')),
                ('occurrence_month', models.CharField(blank=True, max_length=2, verbose_name='ماه رویداد')),
                ('occurrence_year', models.CharField(blank=True, max_length=4, verbose_name='سال رویداد')),
                ('time_utc', models.CharField(blank=True, max_length=20, verbose_name='زمان UTC')),
                ('time_local', models.CharField(blank=True, max_length=20, verbose_name='زمان محلی')),
                ('time_of_day', models.CharField(blank=True, choices=[('daylight', 'روز'), ('dawn', 'سپیده\u200cدم'), ('night', 'شب'), ('dusk', 'غروب')], max_length=20, verbose_name='وضعیت زمان')),
                ('route_from', models.CharField(blank=True, max_length=100, verbose_name='مبدا')),
                ('route_to', models.CharField(blank=True, max_length=100, verbose_name='مقصد')),
                ('ac_type', models.CharField(blank=True, max_length=50, verbose_name='نوع هواپیما')),
                ('ac_registration', models.CharField(blank=True, max_length=50, verbose_name='ثبت هواپیما')),
                ('crew_count', models.CharField(blank=True, max_length=10, verbose_name='تعداد خدمه')),
                ('pax_count', models.CharField(blank=True, max_length=10, verbose_name='تعداد مسافر')),
                ('flight_number', models.CharField(blank=True, max_length=50, verbose_name='شماره پرواز')),
                ('flight_phase', models.JSONField(blank=True, default=list, verbose_name='فاز پرواز')),
                ('occurrence_type_37', models.JSONField(blank=True, default=list, verbose_name='نوع رویداد ۳۷')),
                ('occurrence_type_b', models.JSONField(blank=True, default=list, verbose_name='رفتار مسافر B')),
                ('occurrence_type_c', models.JSONField(blank=True, default=list, verbose_name='اقدامات خدمه C')),
                ('occurrence_type_d', models.JSONField(blank=True, default=list, verbose_name='رویدادهای عمومی D')),
                ('occurrence_type_e', models.JSONField(blank=True, default=list, verbose_name='مشکلات فنی E')),
                ('description', models.TextField(blank=True, verbose_name='توضیح رویداد (۳۸)')),
                ('other_info_suggestions', models.TextField(blank=True, verbose_name='اطلاعات دیگر و پیشنهاد اقدام پیشگیرانه (۳۹)')),
                ('submission_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabin_safety_reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش اجباری ایمنی کابین',
                'verbose_name_plural': 'گزارش\u200cهای اجباری ایمنی کابین',
                'ordering': ['-created_at'],
            },
        ),
    ]
