# Generated by Django 4.2.2 on 2026-02-18 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0008_add_cabin_safety_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyHazardReportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('reporter_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('section', models.CharField(blank=True, max_length=200, verbose_name='واحد سازمانی')),
                ('tel', models.CharField(blank=True, max_length=50, verbose_name='تلفن تماس')),
                ('report_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ')),
                ('report_number', models.CharField(blank=True, max_length=50, verbose_name='شماره گزارش')),
                ('ac_registration', models.CharField(blank=True, max_length=50, verbose_name='ثبت هواپیما')),
                ('type_of_hazard', models.JSONField(blank=True, default=list, verbose_name='نوع مخاطره')),
                ('type_of_hazard_others', models.CharField(blank=True, max_length=200, verbose_name='سایر نوع مخاطره')),
                ('spec_time', models.CharField(blank=True, max_length=50, verbose_name='زمان')),
                ('spec_date', models.CharField(blank=True, max_length=50, verbose_name='تاریخ مشخصات')),
                ('spec_location', models.CharField(blank=True, max_length=200, verbose_name='مکان')),
                ('hazard_description', models.TextField(blank=True, verbose_name='توضیحات دقیق مخاطره / شرح جزئیات خطر')),
                ('safety_director_decision', models.TextField(blank=True, verbose_name='تصمیم مدیر ایمنی')),
                ('director_actions', models.JSONField(blank=True, default=dict, verbose_name='اقدامات مدیر')),
                ('director_name', models.CharField(blank=True, max_length=200, verbose_name='نام مدیر ایمنی')),
                ('sign_and_date', models.CharField(blank=True, max_length=200, verbose_name='امضا و تاریخ')),
                ('submission_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_hazard_reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش مخاطرات ایمنی',
                'verbose_name_plural': 'گزارش\u200cهای مخاطرات ایمنی',
                'ordering': ['-created_at'],
            },
        ),
    ]
