# Generated by Django 5.2.6 on 2025-11-22 11:54

import blog.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(help_text='اسلاگ یکتا برای URL', max_length=100, unique=True, validators=[blog.validators.validate_slug], verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان برای SEO (حداکثر 60 کاراکتر)', max_length=60, null=True, validators=[blog.validators.validate_meta_title], verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, help_text='توضیحات برای SEO (حداکثر 160 کاراکتر)', max_length=160, null=True, validators=[blog.validators.validate_meta_description], verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, help_text='کلمات کلیدی جدا شده با کاما', max_length=255, null=True, verbose_name='کلمات کلیدی متا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/categories/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='blog_catego_slug_6fa4e9_idx'), models.Index(fields=['is_active', 'order'], name='blog_catego_is_acti_2c46c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='اسلاگ یکتا برای URL', max_length=200, unique=True, validators=[blog.validators.validate_slug], verbose_name='اسلاگ')),
                ('excerpt', models.TextField(help_text='خلاصه مقاله (حداکثر 500 کاراکتر)', max_length=500, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوای کامل')),
                ('article_type', models.CharField(choices=[('BLOG', 'وبلاگ'), ('NEWS', 'خبر'), ('GUIDE', 'راهنما'), ('FAQ', 'سوالات متداول')], db_index=True, default='BLOG', max_length=20, verbose_name='نوع مقاله')),
                ('featured_image', models.ImageField(blank=True, help_text='تصویر اصلی مقاله', null=True, upload_to='blog/articles/', verbose_name='تصویر شاخص')),
                ('image_alt', models.CharField(blank=True, help_text='متن جایگزین برای SEO', max_length=200, null=True, verbose_name='متن جایگزین تصویر')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان برای SEO (حداکثر 60 کاراکتر)', max_length=60, null=True, validators=[blog.validators.validate_meta_title], verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, help_text='توضیحات برای SEO (حداکثر 160 کاراکتر)', max_length=160, null=True, validators=[blog.validators.validate_meta_description], verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, help_text='کلمات کلیدی جدا شده با کاما', max_length=255, null=True, verbose_name='کلمات کلیدی متا')),
                ('seo_priority', models.CharField(choices=[('LOW', 'کم'), ('NORMAL', 'متوسط'), ('HIGH', 'بالا'), ('CRITICAL', 'بسیار بالا')], db_index=True, default='NORMAL', max_length=20, verbose_name='اولویت SEO')),
                ('og_title', models.CharField(blank=True, help_text='عنوان برای شبکه\u200cهای اجتماعی', max_length=60, null=True, verbose_name='عنوان Open Graph')),
                ('og_description', models.CharField(blank=True, help_text='توضیحات برای شبکه\u200cهای اجتماعی', max_length=160, null=True, verbose_name='توضیحات Open Graph')),
                ('og_image', models.ImageField(blank=True, help_text='تصویر برای اشتراک\u200cگذاری در شبکه\u200cهای اجتماعی', null=True, upload_to='blog/og-images/', verbose_name='تصویر Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='URL کانونیکال برای جلوگیری از محتوای تکراری', null=True, verbose_name='Canonical URL')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشر شده'), ('ARCHIVED', 'بایگانی شده'), ('PENDING', 'در انتظار بررسی')], db_index=True, default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='ثابت')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='اجازه نظر')),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید')),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='زمان تقریبی مطالعه مقاله', verbose_name='زمان مطالعه (دقیقه)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی به صورت JSON', verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='تاریخ و زمان انتشار مقاله', null=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='داده\u200cهای JSON-LD برای Google', verbose_name='داده\u200cهای ساختاریافته')),
                ('schema_markup', models.TextField(blank=True, help_text='Schema.org markup برای SEO', null=True, verbose_name='Schema.org Markup')),
                ('robots_index', models.BooleanField(default=True, verbose_name='اجازه ایندکس')),
                ('robots_follow', models.BooleanField(default=True, verbose_name='اجازه فالو')),
                ('robots_noarchive', models.BooleanField(default=False, verbose_name='عدم بایگانی')),
                ('robots_nosnippet', models.BooleanField(default=False, verbose_name='عدم نمایش خلاصه')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, help_text='اولویت از 0.0 تا 1.0', max_digits=2, verbose_name='اولویت در Sitemap')),
                ('sitemap_changefreq', models.CharField(choices=[('always', 'همیشه'), ('hourly', 'ساعتی'), ('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('yearly', 'سالانه'), ('never', 'هرگز')], default='weekly', max_length=20, verbose_name='فرکانس تغییر در Sitemap')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_data', to='blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'اطلاعات SEO',
                'verbose_name_plural': 'اطلاعات SEO',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, validators=[blog.validators.validate_slug], verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, validators=[blog.validators.validate_meta_description], verbose_name='توضیحات متا')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='blog_tag_slug_867cce_idx')],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('SPAM', 'اسپم')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='آی\u200cپی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='نظر والد')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'status'], name='blog_commen_article_859ffc_idx'), models.Index(fields=['status', 'created_at'], name='blog_commen_status_399a2d_idx'), models.Index(fields=['ip_address'], name='blog_commen_ip_addr_760826_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug', 'status'], name='blog_articl_slug_a74839_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='blog_articl_status_8b18ca_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='blog_articl_categor_ff847e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status'], name='blog_articl_author__00152e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', 'status'], name='blog_articl_is_feat_e2453a_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['view_count'], name='blog_articl_view_co_3cd54e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['seo_priority', 'status'], name='blog_articl_seo_pri_b111e5_idx'),
        ),
    ]
