# Generated by Django 4.2.2 on 2025-11-22 13:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='backlink_count',
            field=models.PositiveIntegerField(default=0, help_text='تعداد بک لینک\u200cهای دریافت شده', verbose_name='تعداد بک لینک'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_length',
            field=models.PositiveIntegerField(default=0, help_text='تعداد کاراکترهای محتوا', verbose_name='طول محتوا'),
        ),
        migrations.AddField(
            model_name='article',
            name='external_link_count',
            field=models.PositiveIntegerField(default=0, help_text='تعداد لینک\u200cهای خارجی در مقاله', verbose_name='تعداد لینک خارجی'),
        ),
        migrations.AddField(
            model_name='article',
            name='h1_title',
            field=models.CharField(blank=True, help_text='عنوان اصلی مقاله (H1) - برای SEO بسیار مهم است', max_length=200, null=True, verbose_name='عنوان H1'),
        ),
        migrations.AddField(
            model_name='article',
            name='h2_count',
            field=models.PositiveIntegerField(default=0, help_text='تعداد هدینگ\u200cهای H2 در محتوا', verbose_name='تعداد H2'),
        ),
        migrations.AddField(
            model_name='article',
            name='h3_count',
            field=models.PositiveIntegerField(default=0, help_text='تعداد هدینگ\u200cهای H3 در محتوا', verbose_name='تعداد H3'),
        ),
        migrations.AddField(
            model_name='article',
            name='h4_count',
            field=models.PositiveIntegerField(default=0, help_text='تعداد هدینگ\u200cهای H4 در محتوا', verbose_name='تعداد H4'),
        ),
        migrations.AddField(
            model_name='article',
            name='internal_link_count',
            field=models.PositiveIntegerField(default=0, help_text='تعداد لینک\u200cهای داخلی در مقاله', verbose_name='تعداد لینک داخلی'),
        ),
        migrations.AddField(
            model_name='article',
            name='keyword_density',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='چگالی کلمه کلیدی اصلی (درصد)', max_digits=5, verbose_name='چگالی کلمه کلیدی'),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.PositiveIntegerField(default=0, help_text='تعداد کلمات در محتوا', verbose_name='تعداد کلمات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='محتوای کامل مقاله با ویرایشگر پیشرفته', verbose_name='محتوای کامل'),
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('anchor_text', models.CharField(help_text='متن لینک که کاربر می\u200cبیند', max_length=200, verbose_name='متن لنگر')),
                ('link_position', models.CharField(choices=[('content', 'در محتوا'), ('excerpt', 'در خلاصه'), ('related', 'در مقالات مرتبط')], default='content', max_length=20, verbose_name='موقعیت لینک')),
                ('is_follow', models.BooleanField(default=True, help_text='آیا لینک follow باشد یا nofollow', verbose_name='Follow Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_links', to='blog.article', verbose_name='مقاله مبدأ')),
                ('target_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_backlinks', to='blog.article', verbose_name='مقاله مقصد')),
            ],
            options={
                'verbose_name': 'لینک داخلی',
                'verbose_name_plural': 'لینک\u200cهای داخلی',
                'indexes': [models.Index(fields=['source_article', 'target_article'], name='blog_intern_source__d343f2_idx'), models.Index(fields=['is_follow'], name='blog_intern_is_foll_f8d414_idx')],
                'unique_together': {('source_article', 'target_article', 'anchor_text')},
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('url', models.URLField(help_text='آدرس کامل لینک خارجی', max_length=500, verbose_name='آدرس URL')),
                ('anchor_text', models.CharField(help_text='متن لینک که کاربر می\u200cبیند', max_length=200, verbose_name='متن لنگر')),
                ('domain', models.CharField(db_index=True, help_text='دامنه لینک خارجی', max_length=200, verbose_name='دامنه')),
                ('is_follow', models.BooleanField(default=False, help_text='لینک\u200cهای خارجی معمولاً nofollow هستند', verbose_name='Follow Link')),
                ('is_sponsored', models.BooleanField(default=False, help_text='آیا لینک اسپانسر شده است', verbose_name='لینک اسپانسر شده')),
                ('link_position', models.CharField(choices=[('content', 'در محتوا'), ('excerpt', 'در خلاصه'), ('footer', 'در فوتر')], default='content', max_length=20, verbose_name='موقعیت لینک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'لینک خارجی',
                'verbose_name_plural': 'لینک\u200cهای خارجی',
                'indexes': [models.Index(fields=['article', 'domain'], name='blog_extern_article_d6bc66_idx'), models.Index(fields=['is_follow', 'is_sponsored'], name='blog_extern_is_foll_af4528_idx')],
            },
        ),
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('source_url', models.URLField(help_text='آدرس کامل صفحه\u200cای که به ما لینک داده', max_length=500, unique=True, verbose_name='آدرس منبع')),
                ('source_domain', models.CharField(db_index=True, help_text='دامنه سایت منبع', max_length=200, verbose_name='دامنه منبع')),
                ('anchor_text', models.CharField(blank=True, help_text='متن لینک در صفحه منبع', max_length=200, null=True, verbose_name='متن لنگر')),
                ('domain_authority', models.PositiveIntegerField(blank=True, help_text='Domain Authority سایت منبع (0-100)', null=True, verbose_name='Domain Authority')),
                ('is_follow', models.BooleanField(default=True, help_text='آیا لینک follow است', verbose_name='Follow Link')),
                ('link_type', models.CharField(choices=[('dofollow', 'DoFollow'), ('nofollow', 'NoFollow'), ('sponsored', 'Sponsored'), ('ugc', 'User Generated Content')], default='dofollow', max_length=20, verbose_name='نوع لینک')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('broken', 'شکسته'), ('removed', 'حذف شده')], db_index=True, default='active', max_length=20, verbose_name='وضعیت')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ کشف')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='آخرین بررسی')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای مربوط به این بک لینک', null=True, verbose_name='یادداشت\u200cها')),
                ('target_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlinks', to='blog.article', verbose_name='مقاله مقصد')),
            ],
            options={
                'verbose_name': 'بک لینک',
                'verbose_name_plural': 'بک لینک\u200cها',
                'indexes': [models.Index(fields=['target_article', 'status'], name='blog_backli_target__b3bc62_idx'), models.Index(fields=['source_domain', 'domain_authority'], name='blog_backli_source__0073a6_idx'), models.Index(fields=['link_type', 'is_follow'], name='blog_backli_link_ty_ec92c0_idx')],
            },
        ),
    ]
