# Generated by Django 4.2.2 on 2025-11-22 13:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_backlink_count_article_content_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='محتوای کامل مقاله با ویرایشگر پیشرفته - می\u200cتوانید تصاویر را آپلود کنید', verbose_name='محتوای کامل'),
        ),
    ]
