# Generated by Django 4.2.2 on 2025-12-27 10:09

import blog.validators
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='IranCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='نام شهر')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(help_text='اسلاگ یکتا برای URL', max_length=100, unique=True, validators=[blog.validators.validate_slug], verbose_name='اسلاگ')),
                ('province', models.CharField(db_index=True, max_length=100, verbose_name='استان')),
                ('province_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان (انگلیسی)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('featured_image', models.ImageField(blank=True, help_text='تصویر اصلی شهر', null=True, upload_to='blog/iran-cities/', verbose_name='تصویر شاخص')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن جایگزین تصویر')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, validators=[blog.validators.validate_meta_title], verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, validators=[blog.validators.validate_meta_description], verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی متا')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'شهر ایران',
                'verbose_name_plural': 'شهرهای ایران',
                'ordering': ['order', 'province', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IranologyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='اسلاگ یکتا برای URL', max_length=200, unique=True, validators=[blog.validators.validate_slug], verbose_name='اسلاگ')),
                ('excerpt', models.TextField(help_text='خلاصه مقاله (حداکثر 500 کاراکتر)', max_length=500, verbose_name='خلاصه')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='محتوای کامل مقاله با ویرایشگر پیشرفته', verbose_name='محتوای کامل')),
                ('featured_image', models.ImageField(blank=True, help_text='تصویر اصلی مقاله', null=True, upload_to='blog/iranology-articles/', verbose_name='تصویر شاخص')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن جایگزین تصویر')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, validators=[blog.validators.validate_meta_title], verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, validators=[blog.validators.validate_meta_description], verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی متا')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشر شده'), ('ARCHIVED', 'بایگانی شده'), ('PENDING', 'در انتظار بررسی')], db_index=True, default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='ویژه')),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید')),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='زمان مطالعه (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iranology_articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.irancity', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'مقاله ایران\u200cشناسی',
                'verbose_name_plural': 'مقالات ایران\u200cشناسی',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='irancity',
            index=models.Index(fields=['slug', 'is_active'], name='blog_iranci_slug_7b527c_idx'),
        ),
        migrations.AddIndex(
            model_name='irancity',
            index=models.Index(fields=['province', 'is_active'], name='blog_iranci_provinc_b6b19e_idx'),
        ),
        migrations.AddIndex(
            model_name='irancity',
            index=models.Index(fields=['is_active', 'order'], name='blog_iranci_is_acti_ff8793_idx'),
        ),
        migrations.AddIndex(
            model_name='iranologyarticle',
            index=models.Index(fields=['slug', 'status'], name='blog_iranol_slug_cfe618_idx'),
        ),
        migrations.AddIndex(
            model_name='iranologyarticle',
            index=models.Index(fields=['city', 'status'], name='blog_iranol_city_id_50aea4_idx'),
        ),
        migrations.AddIndex(
            model_name='iranologyarticle',
            index=models.Index(fields=['status', 'published_at'], name='blog_iranol_status_fdadcb_idx'),
        ),
        migrations.AddIndex(
            model_name='iranologyarticle',
            index=models.Index(fields=['author', 'status'], name='blog_iranol_author__19b983_idx'),
        ),
        migrations.AddIndex(
            model_name='iranologyarticle',
            index=models.Index(fields=['is_featured', 'status'], name='blog_iranol_is_feat_9c1841_idx'),
        ),
    ]
