"""
Constants and choices for bookings app
"""

# Booking Status
BOOKING_PENDING = 'PENDING'
BOOKING_CONFIRMED = 'CONFIRMED'
BOOKING_CANCELLED = 'CANCELLED'
BOOKING_COMPLETED = 'COMPLETED'
BOOKING_REFUNDED = 'REFUNDED'

BOOKING_STATUS_CHOICES = [
    (BOOKING_PENDING, 'در انتظار'),
    (BOOKING_CONFIRMED, 'تأیید شده'),
    (BOOKING_CANCELLED, 'لغو شده'),
    (BOOKING_COMPLETED, 'تکمیل شده'),
    (BOOKING_REFUNDED, 'بازپرداخت شده'),
]

# Booking Type
BOOKING_TYPE_ONE_WAY = 'ONE_WAY'
BOOKING_TYPE_ROUND_TRIP = 'ROUND_TRIP'
BOOKING_TYPE_MULTI_CITY = 'MULTI_CITY'

BOOKING_TYPE_CHOICES = [
    (BOOKING_TYPE_ONE_WAY, 'یک طرفه'),
    (BOOKING_TYPE_ROUND_TRIP, 'رفت و برگشت'),
    (BOOKING_TYPE_MULTI_CITY, 'چند شهر'),
]

# Passenger Type
PASSENGER_ADULT = 'ADULT'
PASSENGER_CHILD = 'CHILD'
PASSENGER_INFANT = 'INFANT'

PASSENGER_TYPE_CHOICES = [
    (PASSENGER_ADULT, 'بزرگسال'),
    (PASSENGER_CHILD, 'کودک'),
    (PASSENGER_INFANT, 'نوزاد'),
]

# Seat Selection Status
SEAT_SELECTED = 'SELECTED'
SEAT_RESERVED = 'RESERVED'
SEAT_AVAILABLE = 'AVAILABLE'
SEAT_OCCUPIED = 'OCCUPIED'

SEAT_STATUS_CHOICES = [
    (SEAT_SELECTED, 'انتخاب شده'),
    (SEAT_RESERVED, 'رزرو شده'),
    (SEAT_AVAILABLE, 'موجود'),
    (SEAT_OCCUPIED, 'اشغال شده'),
]

# Extra Services
EXTRA_INSURANCE = 'INSURANCE'
EXTRA_BAGGAGE = 'BAGGAGE'
EXTRA_MEAL = 'MEAL'
EXTRA_PRIORITY_BOARDING = 'PRIORITY_BOARDING'
EXTRA_LOUNGE_ACCESS = 'LOUNGE_ACCESS'
EXTRA_WIFI = 'WIFI'

EXTRA_SERVICES_CHOICES = [
    (EXTRA_INSURANCE, 'بیمه مسافرتی'),
    (EXTRA_BAGGAGE, 'بار اضافی'),
    (EXTRA_MEAL, 'وعده غذایی'),
    (EXTRA_PRIORITY_BOARDING, 'اولویت سوار شدن'),
    (EXTRA_LOUNGE_ACCESS, 'دسترسی به لانژ'),
    (EXTRA_WIFI, 'WiFi'),
]

# Cancellation Reason
CANCELLATION_USER = 'USER'
CANCELLATION_AIRLINE = 'AIRLINE'
CANCELLATION_WEATHER = 'WEATHER'
CANCELLATION_OTHER = 'OTHER'

CANCELLATION_REASON_CHOICES = [
    (CANCELLATION_USER, 'درخواست کاربر'),
    (CANCELLATION_AIRLINE, 'لغو توسط ایرلاین'),
    (CANCELLATION_WEATHER, 'شرایط آب و هوایی'),
    (CANCELLATION_OTHER, 'سایر'),
]

# Booking Source
BOOKING_SOURCE_WEB = 'WEB'
BOOKING_SOURCE_MOBILE = 'MOBILE'
BOOKING_SOURCE_AGENT = 'AGENT'
BOOKING_SOURCE_CALL_CENTER = 'CALL_CENTER'

BOOKING_SOURCE_CHOICES = [
    (BOOKING_SOURCE_WEB, 'وب‌سایت'),
    (BOOKING_SOURCE_MOBILE, 'موبایل'),
    (BOOKING_SOURCE_AGENT, 'آژانس'),
    (BOOKING_SOURCE_CALL_CENTER, 'مرکز تماس'),
]

# Default Values
DEFAULT_BOOKING_STATUS = BOOKING_PENDING
DEFAULT_BOOKING_TYPE = BOOKING_TYPE_ONE_WAY
DEFAULT_PASSENGER_TYPE = PASSENGER_ADULT

# Cancellation Policies
CANCELLATION_FULL_REFUND_HOURS = 24  # Full refund if cancelled 24+ hours before
CANCELLATION_PARTIAL_REFUND_HOURS = 6  # Partial refund if cancelled 6+ hours before
CANCELLATION_NO_REFUND_HOURS = 0  # No refund if cancelled less than 6 hours before

