# Generated by Django 4.2.2 on 2025-11-18 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import flights.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='شماره ثبت')),
                ('model', models.CharField(db_index=True, max_length=100, verbose_name='مدل')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='سازنده')),
                ('aircraft_type', models.CharField(blank=True, choices=[('NARROW_BODY', 'بدنه باریک'), ('WIDE_BODY', 'بدنه پهن'), ('REGIONAL', 'منطقه\u200cای')], max_length=20, null=True, verbose_name='نوع هواپیما')),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='کل صندلی\u200cها')),
                ('economy_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای اکونومی')),
                ('business_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای بیزینس')),
                ('first_class_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای فرست کلاس')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('in_service_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ورود به خدمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'هواپیما',
                'verbose_name_plural': 'هواپیماها',
                'ordering': ['manufacturer', 'model', 'registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='کد IATA فرودگاه (3 حرف)', max_length=3, unique=True, validators=[flights.validators.validate_airport_code], verbose_name='کد فرودگاه')),
                ('name', models.CharField(max_length=200, verbose_name='نام فرودگاه')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='شهر')),
                ('country', models.CharField(db_index=True, max_length=100, verbose_name='کشور')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('timezone', models.CharField(blank=True, max_length=50, null=True, verbose_name='منطقه زمانی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('flight_count', models.IntegerField(default=0, verbose_name='تعداد پروازها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'فرودگاه',
                'verbose_name_plural': 'فرودگاه\u200cها',
                'ordering': ['country', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_index=True, max_length=20, unique=True, validators=[flights.validators.validate_flight_number], verbose_name='شماره پرواز')),
                ('departure_time', models.DateTimeField(db_index=True, verbose_name='زمان پرواز')),
                ('arrival_time', models.DateTimeField(db_index=True, verbose_name='زمان فرود')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت پرواز')),
                ('economy_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[flights.validators.validate_positive_price], verbose_name='قیمت اکونومی')),
                ('business_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[flights.validators.validate_positive_price], verbose_name='قیمت بیزینس')),
                ('first_class_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[flights.validators.validate_positive_price], verbose_name='قیمت فرست کلاس')),
                ('economy_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای اکونومی موجود')),
                ('business_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای بیزینس موجود')),
                ('first_class_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای فرست کلاس موجود')),
                ('status', models.CharField(choices=[('SCHEDULED', 'برنامه\u200cریزی شده'), ('DELAYED', 'تأخیر'), ('CANCELLED', 'لغو شده'), ('COMPLETED', 'تکمیل شده'), ('BOARDING', 'در حال سوار شدن'), ('DEPARTED', 'پرواز کرده'), ('ARRIVED', 'فرود آمده')], db_index=True, default='SCHEDULED', max_length=20, verbose_name='وضعیت')),
                ('flight_type', models.CharField(choices=[('DIRECT', 'مستقیم'), ('NON_STOP', 'بدون توقف'), ('ONE_STOP', 'یک توقف'), ('MULTI_STOP', 'چند توقف')], default='DIRECT', max_length=20, verbose_name='نوع پرواز')),
                ('gate', models.CharField(blank=True, max_length=10, null=True, verbose_name='گیت')),
                ('terminal', models.CharField(blank=True, max_length=10, null=True, verbose_name='ترمینال')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.aircraft', verbose_name='هواپیما')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport', verbose_name='مقصد')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport', verbose_name='مبدا')),
            ],
            options={
                'verbose_name': 'پرواز',
                'verbose_name_plural': 'پروازها',
                'ordering': ['departure_time'],
            },
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['code'], name='flights_air_code_36cb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['country', 'city'], name='flights_air_country_e643e7_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['is_active'], name='flights_air_is_acti_927562_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['registration_number'], name='flights_air_registr_65db87_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['model'], name='flights_air_model_88826b_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['is_active'], name='flights_air_is_acti_298f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_number'], name='flights_fli_flight__794da4_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['origin', 'destination'], name='flights_fli_origin__ff1479_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time'], name='flights_fli_departu_5bc2af_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['status'], name='flights_fli_status_e6e528_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['origin', 'destination', 'departure_time'], name='flights_fli_origin__ac48a6_idx'),
        ),
    ]
