# Generated by Django 5.2.6 on 2025-11-22 11:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flight',
            name='flights_fli_origin__ac48a6_idx',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddField(
            model_name='airport',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی به صورت JSON', verbose_name='اطلاعات اضافی'),
        ),
        migrations.AddField(
            model_name='airport',
            name='slug',
            field=models.SlugField(blank=True, help_text='برای SEO و URL های دوستانه', max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='airport',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='تاریخ فرود'),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time_only',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت فرود'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='تاریخ پرواز'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time_only',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت پرواز'),
        ),
        migrations.AddField(
            model_name='flight',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی به صورت JSON (مثل شرایط آب و هوا، تاخیرات و...)', verbose_name='اطلاعات اضافی'),
        ),
        migrations.AddField(
            model_name='flight',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='business_seats',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای بیزینس'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='economy_seats',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای اکونومی'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='first_class_seats',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای فرست کلاس'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='کل صندلی\u200cها'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='flight_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد پروازها'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='business_available',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای بیزینس موجود'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='economy_available',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای اکونومی موجود'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='first_class_available',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صندلی\u200cهای فرست کلاس موجود'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['uuid'], name='flights_air_uuid_21b01a_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['uuid'], name='flights_air_uuid_ce2ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['slug'], name='flights_air_slug_eaa09d_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['uuid'], name='flights_fli_uuid_ddc008_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_date'], name='flights_fli_departu_60abbf_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['origin', 'destination', 'departure_date'], name='flights_fli_origin__52e71a_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['status', 'departure_date'], name='flights_fli_status_55049b_idx'),
        ),
    ]
