# Generated by Django 5.2.6 on 2026-01-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_flights_fli_origin__ac48a6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='actual_arrival_time',
            field=models.DateTimeField(blank=True, help_text='زمان واقعی فرود (از API های خارجی)', null=True, verbose_name='زمان واقعی فرود'),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_departure_time',
            field=models.DateTimeField(blank=True, help_text='زمان واقعی پرواز (از API های خارجی)', null=True, verbose_name='زمان واقعی پرواز'),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_gate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='گیت فرود'),
        ),
        migrations.AddField(
            model_name='flight',
            name='delay_minutes',
            field=models.IntegerField(blank=True, help_text='تأخیر پرواز به دقیقه (از API های خارجی)', null=True, verbose_name='تأخیر به دقیقه'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_gate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='گیت پرواز'),
        ),
        migrations.AddField(
            model_name='flight',
            name='stops',
            field=models.PositiveIntegerField(default=0, help_text='تعداد توقف پرواز (می\u200cتواند از FlightDurationTime محاسبه شود)', verbose_name='تعداد توقف'),
        ),
    ]
