# Generated by Django 5.2.6 on 2025-09-28 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('project_created_at', models.DateTimeField(auto_now_add=True)),
                ('project_updated_at', models.DateTimeField(auto_now=True)),
                ('project_status', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('project_priority', models.CharField(max_length=255)),
                ('project_start_date', models.DateTimeField()),
                ('project_end_date', models.DateTimeField()),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_progress', models.IntegerField()),
                ('project_completed', models.BooleanField(default=False)),
                ('project_deleted', models.BooleanField(default=False)),
                ('project_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project_deleted_reason', models.TextField(blank=True, null=True)),
                ('project_deleted_comment', models.TextField(blank=True, null=True)),
                ('project_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('ticket_type', models.CharField(max_length=255)),
                ('ticket_status', models.CharField(max_length=255)),
                ('ticket_category', models.CharField(max_length=255)),
                ('ticket_subcategory', models.CharField(max_length=255)),
                ('ticket_severity', models.CharField(max_length=255)),
                ('ticket_source', models.CharField(max_length=255)),
                ('ticket_source_id', models.CharField(max_length=255)),
                ('ticket_source_url', models.URLField()),
                ('ticket_source_type', models.CharField(max_length=255)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
