# Generated by Django 4.2.2 on 2025-11-18 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_level', models.CharField(choices=[('LOW', 'پایین'), ('NORMAL', 'عادی'), ('HIGH', 'بالا'), ('CRITICAL', 'بحرانی')], db_index=True, default='NORMAL', max_length=20, verbose_name='سطح امنیتی')),
                ('passenger_screening', models.BooleanField(default=True, verbose_name='بررسی مسافران')),
                ('baggage_screening', models.BooleanField(default=True, verbose_name='بررسی بار')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='دستورالعمل\u200cهای ویژه')),
                ('restricted_passengers', models.JSONField(blank=True, default=list, verbose_name='مسافران محدود شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_info', to='flights.flight', verbose_name='پرواز')),
            ],
            options={
                'verbose_name': 'اطلاعات امنیتی',
                'verbose_name_plural': 'اطلاعات امنیتی',
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('PASSENGER', 'مسافر'), ('BAGGAGE', 'بار'), ('AIRPORT', 'فرودگاه'), ('WEATHER', 'آب و هوا'), ('OTHER', 'سایر')], max_length=20, verbose_name='نوع تهدید')),
                ('security_level', models.CharField(choices=[('LOW', 'پایین'), ('NORMAL', 'عادی'), ('HIGH', 'بالا'), ('CRITICAL', 'بحرانی')], default='NORMAL', max_length=20, verbose_name='سطح امنیتی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('RESOLVED', 'حل شده'), ('FALSE_ALARM', 'هشدار کاذب')], db_index=True, default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حل')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای حل')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='flights.flight', verbose_name='پرواز')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='حل شده توسط')),
            ],
            options={
                'verbose_name': 'هشدار امنیتی',
                'verbose_name_plural': 'هشدارهای امنیتی',
                'ordering': ['-created_at'],
            },
        ),
    ]
