"""
Constants and choices for pilots app
"""

# Pilot Status
PILOT_ACTIVE = 'ACTIVE'
PILOT_INACTIVE = 'INACTIVE'
PILOT_ON_LEAVE = 'ON_LEAVE'
PILOT_SUSPENDED = 'SUSPENDED'

PILOT_STATUS_CHOICES = [
    (PILOT_ACTIVE, 'فعال'),
    (PILOT_INACTIVE, 'غیرفعال'),
    (PILOT_ON_LEAVE, 'مرخصی'),
    (PILOT_SUSPENDED, 'معلق'),
]

# Request Type
REQUEST_SCHEDULE_CHANGE = 'SCHEDULE_CHANGE'
REQUEST_FLIGHT_SWAP = 'FLIGHT_SWAP'
REQUEST_LEAVE = 'LEAVE'
REQUEST_ROUTE_CHANGE = 'ROUTE_CHANGE'
REQUEST_DELAY = 'DELAY'
REQUEST_CANCELLATION = 'CANCELLATION'

REQUEST_TYPE_CHOICES = [
    (REQUEST_SCHEDULE_CHANGE, 'تغییر برنامه پروازی'),
    (REQUEST_FLIGHT_SWAP, 'تعویض پرواز'),
    (REQUEST_LEAVE, 'مرخصی'),
    (REQUEST_ROUTE_CHANGE, 'تغییر مسیر پرواز'),
    (REQUEST_DELAY, 'تأخیر'),
    (REQUEST_CANCELLATION, 'لغو پرواز'),
]

# Request Status
REQUEST_PENDING = 'PENDING'
REQUEST_APPROVED = 'APPROVED'
REQUEST_REJECTED = 'REJECTED'
REQUEST_CANCELLED = 'CANCELLED'

REQUEST_STATUS_CHOICES = [
    (REQUEST_PENDING, 'در انتظار'),
    (REQUEST_APPROVED, 'تأیید شده'),
    (REQUEST_REJECTED, 'رد شده'),
    (REQUEST_CANCELLED, 'لغو شده'),
]

# License Type
LICENSE_COMMERCIAL = 'COMMERCIAL'
LICENSE_AIRLINE = 'AIRLINE'
LICENSE_INSTRUCTOR = 'INSTRUCTOR'

LICENSE_TYPE_CHOICES = [
    (LICENSE_COMMERCIAL, 'تجاری'),
    (LICENSE_AIRLINE, 'خطوط هوایی'),
    (LICENSE_INSTRUCTOR, 'مربی'),
]

