# Generated by Django 5.2.6 on 2025-11-18 13:40

import bookings.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=10, unique=True, validators=[bookings.validators.validate_booking_reference], verbose_name='کد رزرو')),
                ('booking_type', models.CharField(choices=[('ONE_WAY', 'یک طرفه'), ('ROUND_TRIP', 'رفت و برگشت'), ('MULTI_CITY', 'چند شهر')], default='ONE_WAY', max_length=20, verbose_name='نوع رزرو')),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'اکونومی'), ('BUSINESS', 'بیزینس'), ('FIRST_CLASS', 'فرست کلاس'), ('PREMIUM_ECONOMY', 'اکونومی پریمیوم')], default='ECONOMY', max_length=20, verbose_name='کلاس کابین')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت پایه')),
                ('extras_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت خدمات اضافی')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مالیات و عوارض')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ کل')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('CONFIRMED', 'تأیید شده'), ('CANCELLED', 'لغو شده'), ('COMPLETED', 'تکمیل شده'), ('REFUNDED', 'بازپرداخت شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('booking_source', models.CharField(choices=[('WEB', 'وب\u200cسایت'), ('MOBILE', 'موبایل'), ('AGENT', 'آژانس'), ('CALL_CENTER', 'مرکز تماس')], default='WEB', max_length=20, verbose_name='منبع رزرو')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='درخواست\u200cهای ویژه')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='دلیل لغو')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight', verbose_name='پرواز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50, verbose_name='نوع سرویس')),
                ('service_name', models.CharField(max_length=200, verbose_name='نام سرویس')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='bookings.booking', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'خدمات اضافی',
                'verbose_name_plural': 'خدمات اضافی',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='ملیت')),
                ('passenger_type', models.CharField(choices=[('ADULT', 'بزرگسال'), ('CHILD', 'کودک'), ('INFANT', 'نوزاد')], default='ADULT', max_length=20, verbose_name='نوع مسافر')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره گذرنامه')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای گذرنامه')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True, validators=[bookings.validators.validate_seat_number], verbose_name='شماره صندلی')),
                ('special_meal', models.BooleanField(default=False, verbose_name='وعده غذایی ویژه')),
                ('wheelchair_assistance', models.BooleanField(default=False, verbose_name='نیاز به ویلچر')),
                ('special_assistance', models.TextField(blank=True, null=True, verbose_name='کمک\u200cهای ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'مسافران',
                'ordering': ['booking', 'passenger_type', 'last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['flight', 'status'], name='bookings_bo_flight__45560d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
    ]
