# Generated by Django 5.2.6 on 2025-11-22 11:54

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('flights', '0002_remove_flight_flights_fli_origin__ac48a6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='آی\u200cپی رزرو'),
        ),
        migrations.AddField(
            model_name='booking',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی رزرو به صورت JSON', verbose_name='اطلاعات اضافی'),
        ),
        migrations.AddField(
            model_name='booking',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['uuid'], name='bookings_bo_uuid_c3e83d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_ip'], name='bookings_bo_booking_c4db66_idx'),
        ),
    ]
