# Generated by Django 5.2.6 on 2026-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_ip_booking_metadata_booking_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='تا این زمان صندلی به\u200cصورت soft-hold قفل است', null=True, verbose_name='انقضای رزرو موقت'),
        ),
        migrations.AddField(
            model_name='booking',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='جلوگیری از دوبار ساختن رزرو با دابل\u200cکلیک', max_length=64, null=True, unique=True, verbose_name='کلید تکرارناپذیر'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('HELD', 'رزرو موقت'), ('CONFIRMED', 'تأیید شده'), ('CANCELLED', 'لغو شده'), ('COMPLETED', 'تکمیل شده'), ('REFUNDED', 'بازپرداخت شده'), ('EXPIRED', 'منقضی شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
    ]
