# Generated by Django 4.2.2 on 2025-11-18 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('FLIGHT', 'پرواز'), ('BOOKING', 'رزرو'), ('PAYMENT', 'پرداخت'), ('PROMOTION', 'پیشنهاد ویژه'), ('SECURITY', 'امنیتی'), ('SYSTEM', 'سیستمی')], db_index=True, max_length=20, verbose_name='نوع اعلان')),
                ('channel', models.CharField(choices=[('EMAIL', 'ایمیل'), ('SMS', 'پیامک'), ('PUSH', 'Push Notification'), ('IN_APP', 'درون برنامه'), ('PHONE', 'تماس تلفنی')], default='EMAIL', max_length=20, verbose_name='کانال')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SENT', 'ارسال شده'), ('DELIVERED', 'تحویل داده شده'), ('FAILED', 'ناموفق'), ('READ', 'خوانده شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('LOW', 'پایین'), ('NORMAL', 'عادی'), ('HIGH', 'بالا'), ('URGENT', 'فوری')], default='NORMAL', max_length=20, verbose_name='اولویت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خواندن')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx')],
            },
        ),
    ]
