# Generated by Django 5.2.6 on 2025-11-22 11:54

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['uuid'], name='notificatio_uuid_052d40_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'status'], name='notificatio_notific_a659f1_idx'),
        ),
    ]
